### ISSUE TITLE
You get an ECONNRESET if the vhost is not existing

### ISSUE THREAD

**Issue by PeterAronZentai** [guidesmiths/rascal#1]
If the rascal config refers to a vhost that is not already created you get an ECONNRESET - instead of a more friendly / descriptive error message

**Comment by cressie176** [comment]
Hi Peter,
Sorry it's been a while. I think this boils down to a choice of yielding the original error (current behaviour) or doing something like...
```
if (err) return cb(new Error(`Error connecting to ${url}. Reason: ${err.message}`))
```
I agree that this would be more friendly, but has the side effect of losing the original stack. Any thoughts?

**Comment by PeterAronZentai** [comment]
I believe if it were just brutally doing a console.error and would do what it does currently might be just as good. Missing vhost is a typical issue, partly cuz you assume vhosts will be wired up as well. The error log would lead to a faster issue resolution.

**Comment by cressie176** [comment]
Improved connection error message will be in the next release.
