### ISSUE TITLE
Issue with using exchange type x-delayed-message with rabbitmq-server 3.8.4-1

### ISSUE THREAD

**Issue by ravihara** [guidesmiths/rascal#100]
Hi,

I have rascal configured with https://github.com/rabbitmq/rabbitmq-delayed-message-exchange (Rabbitmq plugin which provided delayed exchange abilities) and all were working fine till rabbitmq-server 3.8.3-1 on my Ubuntu 18.04 LTS 64 bit system.

When I upgraded rabbitmq-server to 3.8.4-1, the messages do not get added to the delay queue even though the publish method returns a message-id. I have checked with rabbitmq-server core team and they have verified that there is no issue with the plugin or the upgrade.

Hence, I'm suspecting if this could be a corner-case issue with rascal itself (though not really sure). Can you please verify? Thanks.

**Comment by cressie176** [comment]
Hi @ravihara,

It might be, I've never tested publishing it to a non standard exchange. It could also be something in the underlying amqplib, however other whan when the queues are defined, there's nothing I'm aware in either APIs that you need to do differently based on exchange type, so think this is unlikely. 

I'm also unlikely to get time to install a custom exchange type and test locally for a while, so my suggestions would be...

1. Try using confirm channels (even if temporarily) and listening for `success`, `error` and `return` events. The `success` handler will only be called after Rascal receives an acknowledgement from the broker, and the `return` handler will be called if the message was unroutable.  
1. To narrow down the problem, see if you can get a script to publish to the exchange correctly using just amqplib
1. Run with `DEBUG=Rascal:*` to see what's happening under the hood
1. Use [wireshark](https://www.wireshark.org/) to inspect the network traffic. Wireshark has support for AMQP out of the box, so providing you can publish from your local machine it's really easy to workout what's going on. You should see the publish from the client and assuming you're using confirm channels, an acknowledgement back from the broker.

**Comment by ravihara** [comment]
Cool! Thanks for the pointers. I guess, I'll check the handlers stuff first. Failing which, I'll try rest of the points.

**Comment by cressie176** [comment]
Small update - the mandatory flag isn't supported with that plugin, so you won't get a return event. Rascal sets this by default and I'm not sure if that could cause any issues (the documentation doesn't say whether the plugin errors or ignores).

**Comment by ravihara** [comment]
> Small update - the mandatory flag isn't supported with that plugin, so you won't get a return event. Rascal publishes all messages as mandatory by default and I'm not sure if that could cause any issues (the documentation doesn't say whether the plugin errors or ignores).

Thanks you.. I was looking at the same! This could be one of the reasons.. not sure. I'll dig it up a bit. :+1:

**Comment by cressie176** [comment]
Any luck @ravihara?

**Comment by ravihara** [comment]
> Any luck @ravihara?

Nope.. I couldn't do in depth analysis yet. Will keep you posted.

**Comment by ravihara** [comment]
> Any luck @ravihara?

Thanks a ton!! That exactly was the issue. After setting publications._myPubName_.options.mandatory = false, things got sorted.
