### ISSUE TITLE
onConnect event?

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#106]
is there any sort of an on connect event? for the default connection, that I could use to log like the `vhost_initialised` event? this may be a doc bug, or a feature bug.

**Comment by cressie176** [comment]
Hi @xenoterracide,

I'm not quite sure what you mean by "default connection", however there's [no usable connect event](https://github.com/guidesmiths/rascal/issues/85).  

Arguably it's not necessary since `Broker.create` won't yield until all connections have been successfully established (or failed). It would also be problematic with the current design since you can't get access to the broker instance before the connections have been established, it would be too late to register the event handlers. i.e.

```js
const { BrokerAsPromised: Broker } = require('rascal');
const broker = await Broker.create(...)
broker.on('connected', () => { 
  // Too late, the connection already happened
});
```

**Comment by xenoterracide** [comment]
hmm... I was hoping to have some way of doing the `vhost_initialised` so I could basically log where we're connecting to (and that it happened).

My current code prints this on startup

```
info:     connected to amqp://localhost
```

it seems that rascal's debug logging emits this

```
  rascal:tasks:createConnection Connecting to broker using url: amqp://localhost +0ms
```

perhaps the real feature here would be (a PITA for you) to implement a logging facade and have that default to the `debug`  library, or not, I'm not sure. There may be other solutions.

**Comment by cressie176** [comment]
What about exposing something on the broker expose the current set of connection urls (without passwords)? Then you could do

```js
const broker = await Broker.create(...);
logger.info(broker.connectionUrls)
```

Or something similar

**Comment by xenoterracide** [comment]
that would work

**Comment by cressie176** [comment]
Published as rascal@10.2.0

```js
broker.getConnections();
```

```json
[
  { "vhost": "/", "connectionUrl": "amqp://guest:***@localhost:5672?heartbeat=50&connection_timeout=10000&channelMax=100" }
  { "vhost": "other", "connectionUrl": "amqp://guest:***@localhost:5672/other?heartbeat=50&connection_timeout=10000&channelMax=100" }
]
```

**Comment by xenoterracide** [comment]
now all I'll have to do is get this into the @types

**Comment by xenoterracide** [comment]
hmm... I've definitely upgraded

```
    this.log.info('rascal: %o', (broker as any).connectionUrls);
```
definitely connecting

```
  rascal:tasks:createConnection Connecting to broker using url: amqp://localhost +0ms
info:     connected to postgres://localhost:5432/briggo_production
  rascal:tasks:createConnection Obtained connection: c9eb578a-26c2-4344-8f7d-a2524e8451b0 +108m
```

```
yarn list rascal                                                           # service-graph -> feature/RS2-1088-rascal $ ! RC=130
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ rascal@10.2.1
✨  Done in 1.45s.
```

**Comment by cressie176** [comment]
Think it was getConnections()

**Comment by xenoterracide** [comment]
derp, I read the first message not the 2nd, thanks
