### ISSUE TITLE
direct typescript support

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#107]
would be awesome if there was direct typescript support, instead of the thirdparty `@types/rascal` this would mean the types could update with the version, and possibly on things like `broker.on('event'` be stricter typed.

**Comment by cressie176** [comment]
Hi @xenoterracide,

Thanks for the suggestion. I agree that supporting typescript from the rascal repo would mean that the definitions should stay in sync with the rascal releases. Unfortunately it would also increase the maintenance burden, and typescript isn't something that I'm sold on yet. We do use it on some projects, but I find it helps and hinders in equal measure, so not willing to support it at the moment.

**Comment by svrnwnsch** [comment]
Hey did your opinion change on this topic? The current package `@types/rascal` seems to be outdated. I am missing properties like `closeTimeout` which where added in version 14.0 of rascal.
