### ISSUE TITLE
support content validation

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#110]
For a while I've been wanting to validate inbound/outbound messages to see that they conform to the message structure using json schema. Obviously I can hook this myself, but it'd be cool if this was officially supported.

**Comment by cressie176** [comment]
Hi @xenoterracide,

Thanks for the suggestion. There are a variety of different validation packages (e.g. joi, yup, ajv) and I wouldn't want Rascal to make assumptions on which was best, and how they should be configured. Therefore I believe it's best left for the message handler to perform validation.

**Comment by xenoterracide** [comment]
I was thinking maybe that there could be a separate "handler" that sits between the receiver of the content, and could auto respond, but maybe this is hard. I'm not sure.

**Comment by cressie176** [comment]
It's not so much whether it's hard, but doesn't buy very much. It's easy to put the validation in a specific message handler, or to write a pipeline of handlers (a bit like express middleware), or write a base handler that performs validation based on subscription.
