### ISSUE TITLE
check current connection/assertion status

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#120]
Is there a way to check the healthiness of the connection? I'd like to implement it as part of our health check. Obviously I could write my own, but I fear it would be flawed.

**Comment by cressie176** [comment]
Hi @xenoterracide,

You could probably use the broker `error` and `vhost_initialised` events to maintain a list of healthy/unhealthy vhosts.

**Comment by xenoterracide** [comment]
```ts
    broker.on('vhost_initialised', (args) => {
      stateResolver.value = AmqpState.Healthy;
      this.log.info('%O', args);
    });
```
this doesn't seem to be getting called on startup. Maybe because I don't allow it to connect to manager to actually "assert" the vhost (I'm just using the default)

**Comment by cressie176** [comment]
No - it doesn't unfortunately. By the time you get the broker instance, it's already connected, so even if it did emit this event on startup, you would have no way to register an event handler. However if the broker starts successfully, it means the connections are healthy, and you can get connection details from `broker.getConnections()`

**Comment by satazor** [comment]
It seems we can listen to `connect` and `disconnect` events on the broker, as they are forwarded from vhosts. However, we don't know the vhost these events came from, which is fine if you have just one.

Maybe it's worth emitting the connection details on these events, similar to how it's being done in `vhost_initialised`. This would simplify adding a health probe in K8s or similar.

**Comment by satazor** [comment]
At the moment I'm using the `error` and `vhost_initialised` events.

**Comment by cressie176** [comment]
The `connect` and `disconnect` events are redundant and superseded by the `error` and `vhost_intialised` events. 

https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Vhost.js#L403-L404
https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Vhost.js#L61-L62

I don't plan on removing them, since it's an unnecessary breaking change which could cause harm, but I'd rather not encourage their use by making them more useful either.
