### ISSUE TITLE
always connecting as guest?

### ISSUE THREAD

**Issue by xenoterracide** [guidesmiths/rascal#124]
`rabbitmq_1   | PLAIN login refused: user 'guest' - invalid credentials`

```ts
     defaults: {
        connection: {
          url: this.uri,
          user: 'rabbitmq',
          password: 'rabbitmq',
        },
      },
      vhosts: {
        '/': {
```

**Comment by cressie176** [comment]
Try nesting the connection block inside a vhosts block. Also from memory, I think specifying a url means that the configuration will ignore user/password.

**Comment by xenoterracide** [comment]
ironically it was in the vhosts block to begin with, and I've tried putting the credentials in the url.

**Comment by xenoterracide** [comment]
huh, moving it back to the vhost with the uri having the credentials worked, seems like this could be better documented or something...

**Comment by xenoterracide** [comment]
is it a bad idea to use the url? should I be using the other parameters instead?

**Comment by cressie176** [comment]
> huh, moving it back to the vhost with the uri having the credentials worked, seems like this could be better documented or work differently.

Sorry, I don't follow

> is it a bad idea to use the url? should I be using the other parameters instead?

You may find the URLs simpler to read, but if you have config for multiple environments, you would have to repeat a lot of parameters. e.g.

```
amqp://fred:secret1@localhost:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100

amqp://fred:secret2@node1.test.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100
amqp://fred:secret2@node2.test.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100
amqp://fred:secret2@node3.test.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100

amqp://fred:secret3@node1.live.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100
amqp://fred:secret3@node2.live.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100
amqp://fred:secret3@node3.live.example.com:5672/myvhost?heartbeat=10&connection_timeout=10000&channelMax=100
```

**Comment by cressie176** [comment]
This is how defaults & connection config are expected to work...

```
defaults: {
  vhosts: {
    connection: {
      user: "fred"
    }
  }
},
vhosts: {
  a: {
    connection: {
      host: "example1",
      pass: "secret1"
    }
  },
  b: {
    connection: {
      url: "amqp://example2".
      pass: "secret2"
    }
  }
}
    
```

The default config will be merged with vhost a's config and vhost b's config...

```
vhosts: {
  a: {
    connection: {
      host: "example1",
      pass: "secret1",
      user: "fred"
    }
  },
  b: {
    connection: {
      url: "amqp://example2".
      pass: "secret2",
      user: "fred"
    }
  }
}
```
However because vhost b specifies a url, this value trumps all the other properties. It is assumed the URL is complete. As per the [documentation](https://github.com/guidesmiths/rascal#connection) the url and individual details are alternatives, rather than complimentary.

**Comment by cressie176** [comment]
Did you get things resolved @xenoterracide?

**Comment by xenoterracide** [comment]
yes
