### ISSUE TITLE
Counter based on x-death header.

### ISSUE THREAD

**Issue by satazor** [guidesmiths/rascal#125]
It seems that recent versions of RabbitMQ inject a `x-death` header with a `count` property, which includes the number of times the message was re-enqueded. Perhaps we could have a built-in counter that uses that.

**Comment by cressie176** [comment]
Hi @satazor,

Can you point me to the relevant RabbitMQ docs please? As far as I can tell, the x-death header is only added when a message it [dead lettered](https://www.rabbitmq.com/dlx.html), not when it is rolled back.

**Comment by cressie176** [comment]
Maybe you were thinking of the `x-delivery-count` header provided by the new [quorum queues](https://www.rabbitmq.com/quorum-queues.html)?

**Comment by satazor** [comment]
Hello @cressie176.

I’m not sure since I haven’t tested, but it seems that it’s added once you nAck. I will investigate 
 further and reply back.

See also:

- https://www.mon-code.net/post/117/Control-the-number-of-retries-of-a-message-with-x-death-header-in-RabbitMQ
- https://rabbitmq.com/dlx.html#effects (a message is dead lettered if nAck with requeue set to true)

**Comment by cressie176** [comment]
Yes, that was my understanding too - when you nack and the queue is configured with a dead letter exchange, RabbitMQ adds the x-death header and count. This isn't useful for rascal's counter functionality, which is intended to protect against poisoned messages which crash your application, causing a rollback without giving you the opportunity to nack.

**Comment by cressie176** [comment]
If what you want to do is automatically retry a nacked message up to a maximum number of times you can already do this with rascals [republish](https://github.com/guidesmiths/rascal#republish) recovery strategy.

**Comment by satazor** [comment]
@cressie176 Oh I misunderstood the docs. A message that crashes your app will be handled by the counter, which is different from the recovery strategy, where we are explicitly telling that the message failed to be processed.

The only issue I see with the default counters is that for very large deployments, with many consumers running on different logical servers, the crash loop will might take a lot of time to be resolved, as the message would need to traverse all consumer nodes, up to X times. Actually, the loop will be infinite if the processes are restarted in between as the memory would be lost.

Using Redis or some other storage is indeed the only 100% safe way to deal with this.

**Comment by satazor** [comment]
Using a quorum queue would also solve the crash / poisoning, as you mentioned: https://www.rabbitmq.com/quorum-queues.html#poison-message-handling.
