### ISSUE TITLE
Changing header properties of a publisher (content type)

### ISSUE THREAD

**Issue by kresa3333** [guidesmiths/rascal#129]
Hello,

I got 2 micro services. 1 in c# with massTransient (a c# rabbitMq library) and 1 in node.js with rascal.js

In a certain scenario I need to be able to publish a message in my node.js app and consume it in the c# app.
There seem to be an issue with that because I believe the massTransient library requires certain fields.

In order for the c# app to be able to recognize and consume the message It seems that I need to be able to modify the content-type (and maybe the header as well) of the published message with rascal.js. 
So that the final message will have those properties:
![image](https://user-images.githubusercontent.com/10089006/93784957-3a9ca780-fc36-11ea-8804-d705d7d257e1.png)

I tried digging in the readme and implementation of the rascal.js library and from what I can see the only possible way to control it is in the subscriber section (options)? - This is an issue for me since the subscriber is in the c# app.

Maybe there is support for this sort of modification that I missed or miss understood? 
And if there is no support in modification of this sort, can you suggest the right way to implement it?

**Comment by kresa3333** [comment]
I miss understood, it works.

**Comment by cressie176** [comment]
Hi @kresa3333, thanks for the update. I'm glad you got it sorted.
