### ISSUE TITLE
quick question - what is `slashes` option in connection configuration

### ISSUE THREAD

**Issue by matej-prokop** [guidesmiths/rascal#132]
In examples of connection configuration, you have an attribute called `slashes`  (bool) but I can't find for what it is used. Can you please explain what it does? Thank you 

```json
{
  "vhosts": {
    "v1": {
      "connection": {
        "slashes": true,
        "protocol": "amqp",
        "hostname": "localhost",
        "user": "guest",
        "password": "guest",
        "port": 5672,
        "vhost": "v1",
        "options": {
            "heartbeat": 5
        },
        "socketOptions": {
            "timeout": 10000
        }
      }
    }
  }
}
```

**Comment by cressie176** [comment]
Hi @matej-prokop,

The connection attributes get formatted into a URL using Node's [url.format](https://nodejs.org/api/url.html#url_url_format_urlobject). When slashes is true, the resulting url includes slashes after the protocol, i.e. `amqp://....`. Unfortunately this api was deprecated in Node 11, and the replacement API doesn't look anywhere near as friendly for creating urls from objects. I'll see whether [native-url](https://www.npmjs.com/package/native-url#urlformaturlobj) works as well.

**Comment by matej-prokop** [comment]
Great! Thank you very much for explanation 👍
