### ISSUE TITLE
Why do publications and subscriptions share the same connection?

### ISSUE THREAD

**Issue by georgeben** [guidesmiths/rascal#134]
Thanks for this awesome library. however, I have a question, I don't know if I'm doing it wrong but I noticed publications and subscriptions share the same connection (tcp connection). Isn't that problematic?
I read [an article](https://www.cloudamqp.com/blog/2017-12-29-part1-rabbitmq-best-practice.html) on CloudAMQP which suggests that it's best to have separate connections for publishers and consumers. Please I would like a clarification on this, thank you.

**Comment by cressie176** [comment]
Hi @georgeben,

I wasn't aware of CloudAMQP's recommendation when designing Rascal. It hasn't caused us any issues in production so far, but we're not super high thoughput. It's probably possible to do this by configuring Rascal with a second vhost pointing to the same actual vhost. Not ideal though.

Do you mind if I asked you why you closed the ticket?

**Comment by georgeben** [comment]
Hi @cressie176 thank you for your reply. Thank you for your explanation. The reason I closed the ticket was because I thought I might have configured it wrongly. Thank you for pointing this out.

**Comment by itshaadi** [comment]
> Not ideal though.

Could you point out the downside? are there any serious issues with this decision?

**Comment by cressie176** [comment]
Hi @itshaadi,

No serious issues other than having to duplicate the config.
