### ISSUE TITLE
Node JS server is getting restarted when the rabbitMQ got restarted inside a k8s namespace

### ISSUE THREAD

**Issue by nik-vaidya** [guidesmiths/rascal#138]
Hi,

I have a node js app running inside a k8s namespace and the rabbitmq is also running as a micro service in the same namespace
I have used the following rascalConfiguration to connect to the rabbitmq.
`module.exports = {
  "vhosts": {
    "/": {
      "connection": {
        "options": {
          "heartbeat": 10,
          "connection_timeout": 60000
        },
        "retry": {
          "min": 1000,
          "max": 60000,
          "factor": 2,
          "strategy": 'exponential'
        },
        "socketOptions": {
          "timeout": 10000
        }
      },
      "exchanges": [
        "test_exchange"
      ],
      "queues": {
        "my_queue": {
          "options": {
            "arguments": {
              "x-message-ttl": 3600000,
              "x-dead-letter-exchange": "my_dead_exchange",
              "durable": true
            }
          }
        }
      },
      "bindings": ["test_exchange[provider] -> my_queue"],
      "publications": {
        "Some_service": {
          "exchange": "test_exchange",
          "routingKey": "provider",
        }
      },
      "subscriptions": {
        "my_queue": {
          "queue": "my_queue"
        }
      }
    }
  }
}`
Due to some reason, the rabbit MQ pod got restarted, I could see that for the broker created, there was an error event where I logged the error which says 
`Error with rabbitmq connection: write ECONNRESET`

and after some time my server shows this below error and gets restarted.

`events.js:288
      throw er; // Unhandled 'error' event
Error: Heartbeat timeout
    at Heart.<anonymous> (/usr/src/app/node_modules/amqplib/lib/connection.js:427:19)`

can someone help us understand which function/event is causing this so that we can catch it and handle it gracefully

**Comment by cressie176** [comment]
Hi @nik-vaidya,

Did you read the [very important section on event handling](https://github.com/guidesmiths/rascal#very-important-section-about-event-handling) in the rascal readme?

I suspect there's information here which will help.

**Comment by nik-vaidya** [comment]
Hi @cressie176 

I have handled the scenarios as per the above documentation. Still, the pod is crashing and restarting with error `Error: Heartbeat timeout`

**Comment by cressie176** [comment]
AMQP includes a heartbeat feature in the protocol so both client and server can detect dropped connections. When amqplib detects enough missing heartbeats it emits an error from the connection, which will initially [handled](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Vhost.js#L406-L407) by the Rascal Vhost, [re-emitted](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Vhost.js#L415), [forwarded](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/tasks/initVhosts.js#L13) to the broker. Providing you have added an error listener on the broker, then it should not crash your application.

I test this functionality regularly using the [example](https://github.com/guidesmiths/rascal/tree/master/examples/advanced) projects and by killing RabbitMQ in a docker container, so I'm not sure why it might not be working in your environment. I'm happy to review your code if you are able to share it.

PS. Some recommend disabling this on the server and enabling [TCP Keepalive](https://github.com/squaremo/amqp.node/issues/557#issuecomment-606553626) instead.

**Comment by cressie176** [comment]
Reading your issue again, I suspect I may have missed something - apologies for this. It sounds like the original error was handled, but then you received a subsequent heartbeat error. There as a mistake in and older version of rascal, which used `once` instead of `on` and therefore only handled the first error. Are you using the latest version of the library?

**Comment by nik-vaidya** [comment]
Hi @cressie176 
It's working now. The application is not crashing now. Thank you so much for the help.

**Comment by nik-vaidya** [comment]
Just need to confirm one more thing, if rabbitMQ was down and after some time it came up, then rascal will internally try to connect again. So what about subscriptions are they will be still intact?
I observed that subscriptions are intact, just need to check if there is any scenario where I need to subscribe again.

**Comment by cressie176** [comment]
Hi @nik-vaidya,

> Just need to confirm one more thing, if rabbitMQ was down and after some time it came up, then rascal will internally try to connect again. So what about subscriptions are they will be still intact?

Yes, that is correct. Rascal will automatically reconnect and resubscribe as soon as the connection is re-established. There is another scenario when the broker sends a [consumer cancel notification](https://www.rabbitmq.com/consumer-cancel.html), which happens if the queue is deleted. Rascal will automatically attempt to resubscribe then too, but will not automatically recreate the queue unless the connection actually fails or your application is restarted.

> It's working now.

Good news. Out of curiosity what did you do to get it working?

**Comment by nik-vaidya** [comment]
Yeah...so I updated the version and I was throwing an exception on the error subscription event when the rabbit MQ connection was lost and that error was not handled. So I removed the throw statement and after that application was not getting restarted.

Thank you so much @cressie176  for the help

**Comment by cressie176** [comment]
My pleasure.
