### ISSUE TITLE
Promise support?

### ISSUE THREAD

**Issue by breeswish** [guidesmiths/rascal#14]

**Comment by cressie176** [comment]
No. It would increase the complexity of the code base and testing overhead.

**Comment by breeswish** [comment]
Could you expose classes via module.exports (for example, Broker) so that I can use `bluebird.promisifyAll` to provide a promise-style API?

**Comment by cressie176** [comment]
I'll create a branch and do it there. You happy to test / feedback?

**Comment by breeswish** [comment]
It won't be better!
I will use it in our experimental environment :P

**Comment by cressie176** [comment]
Try 

```
{
  "dependencies": {
    "rascal": "git://github.com/guidesmiths/rascal.git#promises"
  }
}
```
```
Promise.promisifyAll(require('rascal').classes)
```

**Comment by breeswish** [comment]
Thanks for your effort. However it doesn't fully work at least for broker (I haven't tried other classes yet) because:

1) Broker does not expose its base class  https://github.com/guidesmiths/rascal/blob/promises/lib/amqp/Broker.js#L17
In this way, broker instance methods such as `broker.publish` won't be promisified.

2) `Broker` does not use prototype to define its methods thus `bluebird.promisifyAll(Object.getPrototypeOf(someBrokerInstance));` will not work either.  

`promisify(someBrokerInstance)` works but it is not ideal because it is not a one-time setup.

I would try to make some changes and will send you PRs whose implementations are friendly to promisify.

**Comment by cressie176** [comment]
Thanks. I'm to accept a PR.

**Comment by breeswish** [comment]
I made first attempt to make Broker promisify friendly:

https://github.com/breeswish/rascal/commit/c62c4a425093fa6fa7ce522605822cb0e021ff5c?w=1

[Simple example](https://github.com/guidesmiths/rascal/blob/master/examples/simple/index.js) rewritten in Promise way and ES 2017:

```js
import bluebird from 'bluebird'
import Rascal from 'rascal'

bluebird.promisifyAll(Rascal.Broker)
bluebird.promisifyAll(Rascal.Broker.prototype)

(async () => {

  const broker = await Rascal.Broker.createAsync(Rascal.withDefaultConfig(config))
  broker.on('error', console.error)

  const subscription = await broker.subscribe('demo_sub')
  subscription
    .on('message', function(message, content, ackOrNack) {
      console.log(content)
      ackOrNack()
    })
    .on('error', console.error)

  setInterval(async () => {
    await publication = broker.publish('demo_pub', new Date().toISOString() + ': hello world')
    publication.on('error', console.error)
  }, 1000)

}())
```

**Comment by breeswish** [comment]
I am going to test the new broker these days to see if there are any problems :P I will make PR later

**Comment by cressie176** [comment]
Looks good to me. Thanks. After submitting the PR how do you feel about maintaining a 'rascal-as-promised' module?

**Comment by breeswish** [comment]
Thanks, I might not be a good person to maintain that since most of the time I am not working with something related to AMQP :P I prefer to making rascal friendly to promisify tools so that users who want to use a promise style API can easily achieve that while rascal needn't care much about the promise API.

**Comment by breeswish** [comment]
Ok seems that the promise way may lose message..caused by `await broker.subscribeAsync('demo_sub')`..

**Comment by cressie176** [comment]
Good spot. It's a weakness in the rascal API that you can't safely go async between calling ```subscribe``` and registering the on message handler.

Couple of things I might be able to do...

1. Accept an optional event handler as part of the ```subscribe``` function.
2. Not start consuming messages until an on message event listener was added using the [newListener](https://nodejs.org/api/events.html#events_event_newlistener) event

**Comment by cressie176** [comment]
Not as easy as I'd hoped. 

1. Would need to take multiple event handlers ('message', 'invalid_message', 'error', 'redeliveries_exceeded')
2. Breaks the subscrition.cancel behaviour.

**Comment by breeswish** [comment]
Agree with you. BTW Promise is at least a microtask so that changing API is unavoidable to support Promise. This functionality is more difficult than I thought :P

**Comment by cressie176** [comment]
I think the API will be better if the user can subscribe to events before starting to consume messages from rabbit, so I'm still giving it some thought. I have a lot of other stuff on at the moment though so it won't be soon though.

**Comment by cressie176** [comment]
@BorePlusPlus just came up with a nice idea. Instead of consuming messages immediately, if rascal could wait for an `on('message')` handler to be registered. Will investigate

**Comment by mixecan** [comment]
> @BorePlusPlus just came up with a nice idea. Instead of consuming messages immediately, if rascal could wait for an `on('message')` handler to be registered. Will investigate

Any change we can see this on the master branch?

**Comment by cressie176** [comment]
Currently available on the promise-support branch. I'll publish once I've done some more testing and had it reviewed.

**Comment by cressie176** [comment]
Release as 4.0.0
