### ISSUE TITLE
RPC example

### ISSUE THREAD

**Issue by matte0080** [guidesmiths/rascal#144]
Hi mate,

thank you for you great library, it's a rocks! I have spend  a lot of time to try implement RPC Call between two web service in the cloud but without success. I don't understand as implement it. Have you an example, please? 

Thank you, have a nice day.

**Comment by cressie176** [comment]
Hi @matte0080,

Sorry, I don't have any RPC examples, however [amqplib](https://github.com/squaremo/amqp.node) does have one. Here's the [client](https://github.com/squaremo/amqp.node/blob/main/examples/tutorials/rpc_client.js) and here's the [server](https://github.com/squaremo/amqp.node/blob/main/examples/tutorials/rpc_server.js). For the avoidance of doubt, amqplib (and therefore rascal) won't run in the browser, so this is only useful for server->server calls.

If you haven't found it already the RabbitMQ [tutorial](https://www.rabbitmq.com/tutorials/tutorial-six-javascript.html) does cover RPC too.

Hope that helps.
