### ISSUE TITLE
Force shared exchanges and queues to override namespace

### ISSUE THREAD

**Issue by Derwaan** [guidesmiths/rascal#152]
Hi there,

I would like to declare a namespace for my application so that every queue and exchange that my application declares is prefixed with the corresponding namespace. For this, I am using the `namespace` configuration and everything works fine.

But I would also like to declare shared queues or exchanges that should not be prefixed with the namespace as they are created by another application. 

How can I solve this? 

Thanks for your time!

**Comment by cressie176** [comment]
Hi Derwaan,

This wasn't the intended purpose of namespaces - they were designed so applications could be tested in isolation against the same RabbitMQ broker. If I understand correctly you want to enforce a specific queue/exchange format.

There are two approaches I think you could take to achieve this...

1. Generate, pre-process or validate the config before passing it to rascal
2. Define two vhosts with the same connection details.

I would go for (1), as the latter would lead to a fair amount of duplication. It may have other side effects which I can't think of right now too.

**Comment by Derwaan** [comment]
Thanks for your feedback! I will go with solution (1) and generate my configuration.

**Comment by Derwaan** [comment]
Thanks for your feedback! I will go with solution (1) and generate my configuration.
