### ISSUE TITLE
Nacking after republishing with DLQ configured via policy

### ISSUE THREAD

**Issue by humanamburu** [guidesmiths/rascal#155]
Hello,

I have weird behavior when using the dead-letter-exchange policy and republish strategy together. 

I created a queue using the config:
```
    vhosts: {
        '/': {
            connection: {
                url: config.get('messageBus')?.url,
                options: {
                    heartbeat: 1,
                },
                socketOptions: {
                    timeout: 5000,
                },
                retry: {
                    factor: 2,
                    strategy: 'exponential',
                    delay: 1000,
                    max: 10,
                },
            },
            exchanges: ['exchange', 'dead-letters-exchange'],
            queues: {
                'queue': {},
                'dead-letters-queue': {},
            },
            bindings: [
                'exchange[key] -> queue',
                'dead-letters-exchange[key] -> dead-letters-queue',
            ],
            ///.....
        },
    }
```
To avoid complex redeployments I decided to configure dead letter exchange using policy:

```
Pattern | queue
dead-letter-exchange: dead-letters-exchange
```
## Issue:

And when I do the nacking with the default strategy or with `{ strategy: 'nack' }` it works, and I can see message in the `dead-letters-queue`.

But when I use this configuration:
```javascript
const RECOVERY_STRATEGY: Recovery[] = [{ strategy: 'republish', defer: 15000, attempts: 3 }, { strategy: 'nack' }];

ackOrNack(err, RECOVERY_STRATEGY);
```

It retries 3 times and the message just disappears. Could you please take a look? Maybe I'm missing something or can help to fix this by contributing.

Thank you in advance!

**Comment by cressie176** [comment]
Hi @humanamburu,

I don't see where you've configured the work queue to nack messges to the dead letter exchange. You should have something like [this](https://github.com/guidesmiths/rascal/blob/master/examples/advanced/config.js#L43-L49)

This doesn't explain how the message ends up on the DLQ with the single 'nack' strategy though.

Running with `DEBUG=rascal:*` would shed more light on what's happening under the hood.

**Comment by humanamburu** [comment]
@cressie176 thank you for the quick response! 

I used [policies](https://www.rabbitmq.com/parameters.html#policies) to configure dead lettering on the rabbitmq level to avoid complex redeployments. 

<img width="1332" alt="Screenshot 2021-06-17 at 10 40 27" src="https://user-images.githubusercontent.com/14282222/122362596-8d528800-cf58-11eb-8048-a1365302099e.png">


Thanks, I'll try to enable additional logs.

**Comment by humanamburu** [comment]
@cressie176 I would like to kindly ask you do u have any ideas? I checked the logs but still not able to find a solution. 

It works if you specify DLX in the queue params. But using config params requires a complex redeployment strategy for production.

**Comment by cressie176** [comment]
It seems odd that things work with the policy when you have a single recovery strategy but not multiple ones, but only when using the policy, not when using queue arguments. The only thing Rascal does with the queue arguments is add a namespace if you have enabled them - I doubt this, since they're only useful for isolating queues during test runs. Is my understanding of the issue correct or did I confuse something?

When you say you checked the logs, had you enabled Rascal's debug mode? You can do this by setting the `DEBUG` environment variable to `rascal:*` or `rascal:SubscriberError*`. If so you should have seen [this](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/SubscriberError.js#L14) message being logged repeatedly, and also the [publish](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/SubscriberError.js#L64) debug, which should have given some very clear insights what was happening.

Looking at your configuration again, it could also be the binding keys. You posted the following config...
```
            bindings: [
                'exchange[key] -> queue',
                'dead-letters-exchange[key] -> dead-letters-queue',
            ],
```

However I don't know how your dead-letters-exchange is configured to route to the dead-letters-queue. If it's a topic exchange and not bound with a compatible key, the message would be unroutable, but this still wouldn't explain how it worked with a single recovery strategy and not the multiple one. To help further I will need to see the debug.

**Comment by humanamburu** [comment]
@cressie176 Yes, you get everything correctly. Please check the logs below, I did testing with the same message, routing key and etc only changing the recovery strategy from default to `[{ strategy: 'republish', defer: 15000, attempts: 3 }, { strategy: 'nack' }]`;

1. Everything works correctly and the message appears in the `dead-letters-queue` 
```log
  rascal:config:configure Configuring vhost: / +0ms
  rascal:config:configure Configuring exchange: exchange +3ms
  rascal:config:configure Configuring exchange: dead-letters-exchange +0ms
  rascal:config:configure Configuring exchange:  +0ms
  rascal:config:configure Configuring queue: queue +1ms
  rascal:config:configure Configuring queue: dead-letters-queue +0ms
  rascal:config:configure Configuring binding: exchange[scheduling] -> queue +2ms
  rascal:config:configure Configuring binding: dead-letters-exchange[scheduling] -> dead-letters-queue +0ms
  rascal:config:configure Configuring publication: platform +0ms
  rascal:config:configure Configuring subscription: main +0ms
  rascal:config:configure Configuring publication: platform +0ms
  rascal:config:configure Configuring publication: /exchange +1ms
  rascal:config:configure Configuring publication: /dead-letters-exchange +0ms
  rascal:config:configure Configuring publication: / +0ms
  rascal:config:configure Configuring publication: /queue +0ms
  rascal:config:configure Configuring publication: /dead-letters-queue +0ms
  rascal:config:configure Configuring subscription: main +0ms
  rascal:config:configure Configuring subscription: /queue +0ms
  rascal:config:configure Configuring subscription: /dead-letters-queue +0ms
  rascal:config:configure Configuring counter: stub +0ms
  rascal:Broker Initialising broker +0ms
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672 +0ms
  rascal:tasks:createConnection Obtained connection: 10398b58-5f9f-459b-b35e-11c07e448208 +44ms
  rascal:tasks:createChannel Creating channel +0ms
  rascal:tasks:assertExchanges Asserting exchange: exchange +0ms
  rascal:tasks:assertExchanges Asserting exchange: dead-letters-exchange +3ms
  rascal:tasks:assertQueues Asserting queue: queue +0ms
  rascal:tasks:assertQueues Asserting queue: dead-letters-queue +8ms
  rascal:tasks:applyBindings Binding queue: queue to exchange: exchange with binding key: scheduling +0ms
  rascal:tasks:applyBindings Binding queue: dead-letters-queue to exchange: dead-letters-exchange with binding key: scheduling +8ms
  rascal:tasks:closeChannel Closing channel +0ms
  rascal:Vhost Creating regular channel pool { autostart: false, max: 5, min: 1, evictionRunIntervalMillis: 10000, idleTimeoutMillis: 60000, rejectionDelayMillis: 1000, testOnBorrow: true } +98ms
  rascal:Vhost Creating confirm channel pool { autostart: false, max: 5, min: 1, evictionRunIntervalMillis: 10000, idleTimeoutMillis: 60000, rejectionDelayMillis: 1000, testOnBorrow: true } +1ms
  rascal:Vhost vhost: / was initialised with connection: 10398b58-5f9f-459b-b35e-11c07e448208 +0ms
  rascal:Publication Initialising publication: platform +0ms
  rascal:Publication Initialising publication: /exchange +0ms
  rascal:Publication Initialising publication: /dead-letters-exchange +0ms
  rascal:Publication Initialising publication: / +0ms
  rascal:Publication Initialising publication: /queue +0ms
  rascal:Publication Initialising publication: /dead-letters-queue +0ms
  rascal:Subscription Initialising subscription: main +0ms
  rascal:Subscription Initialising subscription: /queue +0ms
  rascal:Subscription Initialising subscription: /dead-letters-queue +0ms
  rascal:Subscription Subscribing to queue: queue +17ms
  rascal:Vhost Requested channel. Outstanding channel requests: 1 +18ms
  rascal:Vhost Created confirm channel: 52033b77-52ea-4a1a-9006-ab1d5c939c86 from connection: 10398b58-5f9f-459b-b35e-11c07e448208 +17ms
  rascal:SubscriberSession Opening subscriber session: amq.ctag-kcDPmI3oY1gLlrxPN2wzHA on channel: 52033b77-52ea-4a1a-9006-ab1d5c939c86 +0ms
  rascal:Subscription Received message: undefined from queue: queue +2m
  rascal:SubscriberError Handling subscriber error for message: undefined +0ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: fallback-nack +1ms
  rascal:SubscriberSession Not acknowledging message: undefined with requeue: false on channel: 52033b77-52ea-4a1a-9006-ab1d5c939c86 +2m
  rascal:SubscriberError Message: undefined was recovered using stragegy: fallback-nack
```

2. Message disappeared (`[{ strategy: 'republish', defer: 15000, attempts: 3 }, { strategy: 'nack' }]`)

```log
  rascal:config:configure Configuring vhost: / +0ms
  rascal:config:configure Configuring exchange: exchange +3ms
  rascal:config:configure Configuring exchange: dead-letters-exchange +0ms
  rascal:config:configure Configuring exchange:  +0ms
  rascal:config:configure Configuring queue: queue +0ms
  rascal:config:configure Configuring queue: dead-letters-queue +0ms
  rascal:config:configure Configuring binding: exchange[scheduling] -> queue +2ms
  rascal:config:configure Configuring binding: dead-letters-exchange[scheduling] -> dead-letters-queue +0ms
  rascal:config:configure Configuring publication: platform +0ms
  rascal:config:configure Configuring subscription: main +0ms
  rascal:config:configure Configuring publication: platform +0ms
  rascal:config:configure Configuring publication: /exchange +1ms
  rascal:config:configure Configuring publication: /dead-letters-exchange +0ms
  rascal:config:configure Configuring publication: / +0ms
  rascal:config:configure Configuring publication: /queue +0ms
  rascal:config:configure Configuring publication: /dead-letters-queue +0ms
  rascal:config:configure Configuring subscription: main +0ms
  rascal:config:configure Configuring subscription: /queue +0ms
  rascal:config:configure Configuring subscription: /dead-letters-queue +0ms
  rascal:config:configure Configuring counter: stub +0ms
  rascal:Broker Initialising broker +0ms
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672 +0ms
  rascal:tasks:createConnection Obtained connection: 284bca33-de48-4fb9-b569-2ac209df9790 +62ms
  rascal:tasks:createChannel Creating channel +0ms
  rascal:tasks:assertExchanges Asserting exchange: exchange +0ms
  rascal:tasks:assertExchanges Asserting exchange: dead-letters-exchange +4ms
  rascal:tasks:assertQueues Asserting queue: queue +0ms
  rascal:tasks:assertQueues Asserting queue: dead-letters-queue +15ms
  rascal:tasks:applyBindings Binding queue: queue to exchange: exchange with binding key: scheduling +0ms
  rascal:tasks:applyBindings Binding queue: dead-letters-queue to exchange: dead-letters-exchange with binding key: scheduling +11ms
  rascal:tasks:closeChannel Closing channel +0ms
  rascal:Vhost Creating regular channel pool { autostart: false, max: 5, min: 1, evictionRunIntervalMillis: 10000, idleTimeoutMillis: 60000, rejectionDelayMillis: 1000, testOnBorrow: true } +133ms
  rascal:Vhost Creating confirm channel pool { autostart: false, max: 5, min: 1, evictionRunIntervalMillis: 10000, idleTimeoutMillis: 60000, rejectionDelayMillis: 1000, testOnBorrow: true } +2ms
  rascal:Vhost vhost: / was initialised with connection: 284bca33-de48-4fb9-b569-2ac209df9790 +0ms
  rascal:Publication Initialising publication: platform +0ms
  rascal:Publication Initialising publication: /exchange +0ms
  rascal:Publication Initialising publication: /dead-letters-exchange +0ms
  rascal:Publication Initialising publication: / +0ms
  rascal:Publication Initialising publication: /queue +0ms
  rascal:Publication Initialising publication: /dead-letters-queue +0ms
  rascal:Subscription Initialising subscription: main +0ms
  rascal:Subscription Initialising subscription: /queue +1ms
  rascal:Subscription Initialising subscription: /dead-letters-queue +0ms
  rascal:Subscription Subscribing to queue: queue +26ms
  rascal:Vhost Requested channel. Outstanding channel requests: 1 +30ms
  rascal:Vhost Created confirm channel: acdb2202-593e-4930-bdfb-319d55e7c1cc from connection: 284bca33-de48-4fb9-b569-2ac209df9790 +19ms
  rascal:SubscriberSession Opening subscriber session: amq.ctag-btdIXeiw-IFttScOGfdd8A on channel: acdb2202-593e-4930-bdfb-319d55e7c1cc +0ms
  rascal:Subscription Received message: undefined from queue: queue +45s
  rascal:SubscriberError Handling subscriber error for message: undefined +0ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: republish +1ms
  rascal:SubscriberError Republishing message: undefined +15s
  rascal:Vhost Requested confirm channel. Outstanding channel requests: 1 +60s
  rascal:Vhost Created confirm channel: b7549132-9204-4cef-a438-c002c95df90d from connection: 284bca33-de48-4fb9-b569-2ac209df9790 +5ms
  rascal:Subscription Received message: undefined from queue: queue +15s
  rascal:SubscriberError Handling subscriber error for message: undefined +17ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: republish +0ms
  rascal:SubscriberError Message: undefined was republished to queue: queue 1 times +2ms
  rascal:SubscriberSession Acknowledging message: undefined on channel: acdb2202-593e-4930-bdfb-319d55e7c1cc +60s
  rascal:SubscriberError Message: undefined was recovered using stragegy: republish +1ms
  rascal:SubscriberError Republishing message: undefined +15s
  rascal:Vhost Requested confirm channel. Outstanding channel requests: 1 +15s
  rascal:Vhost Created confirm channel: 807d06e5-f5da-47a4-9405-3906ab1920b5 from connection: 284bca33-de48-4fb9-b569-2ac209df9790 +15ms
  rascal:Subscription Received message: undefined from queue: queue +15s
  rascal:SubscriberError Handling subscriber error for message: undefined +29ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: republish +0ms
  rascal:SubscriberError Message: undefined was republished to queue: queue 2 times +1ms
  rascal:SubscriberSession Acknowledging message: undefined on channel: acdb2202-593e-4930-bdfb-319d55e7c1cc +15s
  rascal:SubscriberError Message: undefined was recovered using stragegy: republish +1ms
  rascal:SubscriberError Republishing message: undefined +15s
  rascal:Vhost Requested confirm channel. Outstanding channel requests: 1 +15s
  rascal:Vhost Created confirm channel: b35dd071-babe-4b1e-a643-d1f0924a9487 from connection: 284bca33-de48-4fb9-b569-2ac209df9790 +17ms
  rascal:Subscription Received message: undefined from queue: queue +15s
  rascal:SubscriberError Message: undefined was republished to queue: queue 3 times +32ms
  rascal:SubscriberSession Acknowledging message: undefined on channel: acdb2202-593e-4930-bdfb-319d55e7c1cc +15s
  rascal:SubscriberError Message: undefined was recovered using stragegy: republish +0ms
  rascal:SubscriberError Handling subscriber error for message: undefined +2ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: republish +0ms
  rascal:SubscriberError Republishing message: undefined +15s
  rascal:SubscriberError Skipping recovery - message: undefined has already been republished 3 times. +1ms
  rascal:SubscriberError Attempting to recover message: undefined using strategy: nack +0ms
  rascal:SubscriberSession Not acknowledging message: undefined with requeue: false on channel: acdb2202-593e-4930-bdfb-319d55e7c1cc +15s
  rascal:SubscriberError Message: undefined was recovered using stragegy: nack +4ms

```

**Comment by cressie176** [comment]
Hi @humanamburu,

I've tested locally by creating the following policy adding the x-dead-letter-exchange argument with value "dlx" to all queues starting with "work_.*"

![Screenshot 2021-06-22 at 18 24 17](https://user-images.githubusercontent.com/229672/122971714-3ea55380-d387-11eb-9631-bf7d032667e6.png)

I tried by "fanout" and "topic" types for the dead letter exchange, and for the latter, bound the dead letter exchange to a queue (dlq) with a wildcard key of "*"

![Screenshot 2021-06-22 at 18 31 54](https://user-images.githubusercontent.com/229672/122972572-34d02000-d388-11eb-820c-7e6ca45fe2e0.png)

![Screenshot 2021-06-22 at 18 33 05](https://user-images.githubusercontent.com/229672/122972691-516c5800-d388-11eb-8669-fdfe07340d63.png)


Then I ran the following test

```js
  oit('should route message to dlq', (test, done) => {
    createBroker({
      vhosts,
      publications,
      subscriptions,
    }, (err, broker) => {
      assert.ifError(err);
      broker.publish('p1', 'test message', (err) => {
        assert.ifError(err);

        const messages = {};
        broker.subscribe('s1', (err, subscription) => {
          assert.ifError(err);
          subscription.on('message', (message, content, ackOrNack) => {
            assert.ok(message);
            return ackOrNack(new Error('meh'), [{ strategy: 'republish', defer: 100, attempts: 3 }, { strategy: 'nack' }]);          
            done();
          });
        });
      });
    });
  });
```

The output was similar to yours and the message was routed to the dlq each time. I also tried with just a single recovery strategy, and then the default recovery strategy.

I don't have a good explanation as to why this is working in your environment when there are explicit arguments rather than a policy, or with just the default or 'nack' recovery strategies, beyond unlikely ideas about a consumer being attached to your DLQ and swallowing the message before you check it, or the DLQ being setup on a single node in a cluster, rather than being mirrored to each node.

**Comment by humanamburu** [comment]
@cressie176 thank you a lot for your detailed explanation and work! Seems like I found the root cause, but can't understand is it a bug or expected behavior of `rascal`.

I did tests again with the same setup that I listed, but change the binding type from `dead-letters-exchange[key] -> dead-letters-queue` to `dead-letters-exchange[*] -> dead-letters-queue` as you did.

So the root cause is the **wrong routing key** after recovery in this case:

1. Nacking without recovery strategy:

<img width="637" alt="Screenshot 2021-06-23 at 11 30 38" src="https://user-images.githubusercontent.com/14282222/123073133-714a5d00-d416-11eb-8bb7-3321099842fc.png">

2. Nacking with `republish` recovery strategy:
<img width="904" alt="Screenshot 2021-06-23 at 11 33 44" src="https://user-images.githubusercontent.com/14282222/123073630-e027b600-d416-11eb-8a1f-db00ac15dc8a.png">

As you can see, in the 2nd case routing key equals `queue` instead of `key` but I expected that the routing key will be the `originalRoutingKey` even after recoveries.

Is it expected? How can I set up the DLQ login in this case if I have multiple routing keys and different queues per key?

Thank you in advance!

**Comment by cressie176** [comment]
Hi @humanamburu,

Well done. This does explain it (and has taught me something about RabbitMQ that I didn't previously know - thank you).

I hadn't realised that when you nack a message to a dead letter exchange, it will use the original routing key unless overiden by the x-dead-letter-routing-key argument.

When rascal republishes a message it sends it directly to the queue it was received from, rather than to the original exchange using the original routing key if used. This is deliberate in case multiple queues are bound to the original exchange. To do otherwise would mean that all queues received the republished message, rather than just the one which failed and needed recovery.

I can think of two potential improvements to Rascal...

1. Update the documentation and make it clear that nacking a message after a republish may not work as expected
2. Add option to republish to the exchange with the original routing key rather than directly to the queue (but explain how this could be dangerous).

The first is a no-brainer, but I'm less keen on the second.

**Comment by humanamburu** [comment]
@cressie176 nice to know that we found the root cause, thanks.

Is it possible to keep the republish strategy as it is, but restore the original routing key on nacking after republishing? It will make API more consistent IMO.

**Comment by cressie176** [comment]
I'll give it a try, but suspect it won't work. I imagine RabbitMQ will use its own copy of the message when checking the routing.

**Comment by cressie176** [comment]
The [amqp protocol](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.reject.delivery-tag) shows that the reject operation only takes the delivery tag and requeue parameter, so the routing key is never sent back to the server. Also consistent with the [amqplib code](https://github.com/squaremo/amqp.node/blob/32aa2025a20200d0df861d5520bb263ba7b10523/lib/channel_model.js#L231)

**Comment by cressie176** [comment]
> How can I set up the DLQ login in this case if I have multiple routing keys and different queues per key?

I think you will need to bind each DLQ twice. Once with the routing key, and once with the queue name. That way if the message is nacked by your application before being republished, or times out due to a message-ttl, it will be routed to the dead letter exchange using the routing key, but if it is republished then nacked by the recovery strategy, the queue name will be used as the routing key.

**Comment by cressie176** [comment]
I've updated the readme. See point 4 in the [republish](https://github.com/guidesmiths/rascal/blob/master/README.md#republish) recovery strategy section. I don't think there's any more I can do. OK to close?

**Comment by humanamburu** [comment]
@cressie176 thank you a lot for your input, it helps a lot to understand better how it works under the hood.
We applied the workaround you proposed and bind "queue" as a key.

Thanks again.
