### ISSUE TITLE
Connection name

### ISSUE THREAD

**Issue by druny** [guidesmiths/rascal#163]
https://stackoverflow.com/questions/65650010/set-connection-name-with-amqplib

As shown about, Rascal is not supporting customising connection name.

**Comment by cressie176** [comment]
Hi @druny 

Try nesting inside socketOptions. See https://github.com/guidesmiths/rascal/issues/97

**Comment by druny** [comment]
Yes, It works. Thank you :) I think it would be better to describe such opportunities in @types

**Comment by cressie176** [comment]
> I think it would be better to describe such opportunities in @types

As per the rascal [documentation](https://github.com/guidesmiths/rascal#connection), socket options are passed directly through to [amqplib](https://www.squaremobius.net/amqp.node/channel_api.html#connect), so typing them in rascal would tightly couple the two libraries.
