### ISSUE TITLE
Bundle JSONSchema for configuration file

### ISSUE THREAD

**Issue by BANOnotIT** [guidesmiths/rascal#168]
In config files in modern editors you can set root `"$schema": "path/to/schema.json"` and editor will validate current file against specified schema.

You can create jsonschema and bundle it with package, so it can be used as:

```json
{
  "$schema": "../node_modules/rasca/config.schema.json",
  "vhost": {
    ...
  }
  ...
}
```

**Comment by cressie176** [comment]
JSON schema added to `node_modules/rascal/lib/config/schema.json and published in Rascal@14.2.0
Given the complexity/flexibility of the configuration file, there's a good chance it could be improved. I also deliberately avoided making any attributes required, as the configuration could be modified in code.
