### ISSUE TITLE
Process crash with "Callback was already called."

### ISSUE THREAD

**Issue by livey0u** [guidesmiths/rascal#17]
Hi there,

I am getting this error.

```
if (fn === null) throw new Error("Callback was already called.");
                         ^
Error: Callback was already called.
    at /path/to/project/node_modules/async/dist/async.js:903:32
    at /path/to/project/node_modules/async/dist/async.js:2490:13
    at /path/to/project/node_modules/async/dist/async.js:2551:17
    at /path/to/project/node_modules/rascal/lib/amqp/tasks/createConnection.js:24:9
    at /path/to/project/node_modules/async/dist/async.js:4566:26
    at /path/to/project/node_modules/rascal/lib/amqp/tasks/createConnection.js:18:29
    at /path/to/project/node_modules/rascal/lib/amqp/tasks/createConnection.js:32:29
    at /path/to/project/node_modules/amqplib/callback_api.js:16:10
    at /path/to/project/node_modules/amqplib/lib/connect.js:147:12
    at bail (/path/to/project/node_modules/amqplib/lib/connection.js:175:5)
````

Not sure, how this error is created. No other logs. I am not even sure that this is caused from application code or connection related issue triggered in library code.

Thank you!

**Comment by cressie176** [comment]
Sorry you're having problems. Can you answer the following questions please...

* Is this happening when the application is starting or after it's been running for some time?
* How often does it happen
* Has rascal been working reliably in your application before now?

Thanks

**Comment by cressie176** [comment]
I think it's likely to be [this](https://github.com/squaremo/amqp.node/issues/354) issue with [amqplib](https://github.com/squaremo/amqp.node). I can wrap the callback using lodash.once which will stop async hiding the original connection error.

**Comment by livey0u** [comment]
@cressie176, only today I saw this on one of our staging servers. In production, we did not had any issues like this & also no issues with rascal either. My guess is that the problem is because of the connection to rabbitmq got disconnected & reconnected. Due to this error, the process exited. Our process management tool restarted the process & the error kept occurring till the connection is established. Sorry that I couldn't debug further at the moment.

**Comment by cressie176** [comment]
I've wrapped the callback using lodash.once. Published to npm as rascal@1.2.1

**Comment by livey0u** [comment]
Cool. Thank you for providing a solution this quickly.

**Comment by cressie176** [comment]
ok to close?

**Comment by livey0u** [comment]
Sorry. Done!
