### ISSUE TITLE
Add the ability to cancel the channel without forcing it to close

### ISSUE THREAD

**Issue by Hammer-Inc** [guidesmiths/rascal#171]
I'd like to stop consuming messages when I receive a SIGTERM and wait for some long running tasks to complete and ack/nack. before calling broker.shutdown().
 
The deferChannelClose option is not workable as it forces me to wait an arbitrary fixed period of time after which if any tasks are still running they can no longer be acknowledged. Is it possible to add a parameter to avoid calling scheduleClose on the channel? or alternatively expose the channel so I can call cancel directly?

**Comment by cressie176** [comment]
FYI hoping to publish this weekend. Sorry it's been so long.

**Comment by cressie176** [comment]
Published as Rascal@14 (decided to do a single release after all)
