### ISSUE TITLE
Rascal doesn't reconnect if Rabbit is killed

### ISSUE THREAD

**Issue by bradchristensen** [guidesmiths/rascal#18]
If I kill RabbitMQ and immediately restart it, the Rascal service breaks (even after waiting for RabbitMQ to become fully online again) with the following error next time it attempts to use the connection, e.g. for publishing a message. This also causes my app to crash (I assume this means the error is coming from a stream that I can't add an error handler to, but I haven't investigated this too much).

```
0|app      | IllegalOperationError: Connection closed (Error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
0|app      |     at Connection.<anonymous> (/app/node_modules/amqplib/lib/connection.js:359:11)
0|app      |     at ConfirmChannel.C.sendImmediately (/app/node_modules/amqplib/lib/channel.js:64:26)
0|app      |     at ConfirmChannel.C.sendOrEnqueue (/app/node_modules/amqplib/lib/channel.js:75:10)
0|app      |     at ConfirmChannel.C._rpc (/app/node_modules/amqplib/lib/channel.js:131:8)
0|app      |     at ConfirmChannel.Channel.rpc (/app/node_modules/amqplib/lib/callback_model.js:73:8)
0|app      |     at ConfirmChannel.Channel.open (/app/node_modules/amqplib/lib/callback_model.js:86:15)
0|app      |     at CallbackModel.createConfirmChannel (/app/node_modules/amqplib/lib/callback_model.js:285:6)
0|app      |     at createChannel (/app/node_modules/rascal/lib/amqp/Vhost.js:167:38)
0|app      |     at Object.create (/app/node_modules/rascal/lib/amqp/Vhost.js:115:17)
0|app      |     at Pool._createResource (/app/node_modules/generic-pool/lib/generic-pool.js:354:17)
0|app      |     at Pool.dispense [as _dispense] (/app/node_modules/generic-pool/lib/generic-pool.js:314:10)
0|app      |     at Pool.acquire (/app/node_modules/generic-pool/lib/generic-pool.js:436:8)
0|app      |     at /app/node_modules/rascal/lib/amqp/Vhost.js:135:18
0|app      |     at /app/node_modules/rascal/node_modules/async/dist/async.js:4069:9
0|app      |     at process (/app/node_modules/rascal/node_modules/async/dist/async.js:2317:17)
```

This seems to be because Rascal isn't listening for the connection to close and therefore never attempts to recreate the connection. I can fix this by adding the following line into the Vhost init function:

```javascript
ctx.connection.on('close', handleConnectionError.bind(null, config));
```

... such that the code becomes:

```javascript
this.init = function(next) {
    debug('Initialising vhost: %s', config.name)
    pauseChannelAllocation()
    init(config, {}, function(err, config, ctx) {
        if (err) return next(err)
        self.emit('connect')
        ctx.connection.removeAllListeners('error')
        ctx.connection.once('error', handleConnectionError.bind(null, config))
        forwardEvents(ctx.connection, self, function(eventName) {
            return eventName === 'blocked' || eventName === 'unblocked';
        })
        ctx.connection.on('close', handleConnectionError.bind(null, config));
        connection = ctx.connection
        connectionConfig = ctx.connectionConfig
        resumeChannelAllocation()
        return next(null, self)
    })
    return self
}
```

With this line added, when RabbitMQ is killed, the service immediately notices and attempts to retry the connection until it succeeds:

```
0|app      | Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
0|app      | connect ECONNREFUSED 172.18.0.4:5672
0|app      | getaddrinfo ENOTFOUND rabbitmq rabbitmq:5672
0|app      | getaddrinfo ENOTFOUND rabbitmq rabbitmq:5672
0|app      | getaddrinfo ENOTFOUND rabbitmq rabbitmq:5672
0|app      | getaddrinfo ENOTFOUND rabbitmq rabbitmq:5672
0|app      | getaddrinfo ENOTFOUND rabbitmq rabbitmq:5672
0|app      | connect ECONNREFUSED 172.18.0.4:5672
0|app      | connect ECONNREFUSED 172.18.0.4:5672
[...]
0|app      | connect ECONNREFUSED 172.18.0.4:5672
0|app      | connect ECONNREFUSED 172.18.0.4:5672
[ eventually the connection is successful and no more errors are logged ]
```

Furthermore, while the connection is in the retrying state above, attempting to publish messages will not cause the aforementioned error to be thrown and therefore my app does not crash. I have some try-catches in there that are probably swallowing whatever errors are being thrown instead.

This may be naive as I don't understand how all the moving parts in Rascal/amqplib fit together 😅 Just hoping to get your initial thoughts and I'll be happy to investigate further on any of these points if you need me to.

**Comment by cressie176** [comment]
Hi @bradchristensen. Thanks for reporting. Looking into it now. Will get back to you shortly.

**Comment by cressie176** [comment]
I'm having trouble reproducing using kill, however I get the same if I stop RabbitMQ using
```
/bin/sh -e /usr/lib/rabbitmq/bin/rabbitmqctl stop  
```
I'll add an explicit handleConnectionClose function as handleConnectionError expects an error object.

Thanks for your the analysis and suggested fix. Saved me a lot of time.

**Comment by cressie176** [comment]
Looks like the close event passes and error object too.

**Comment by cressie176** [comment]
Works for publishing, but subscriptions suffer a similar problem. I'll add the same fix there.

**Comment by cressie176** [comment]
Published as rascal 1.4.0?

**Comment by cressie176** [comment]
Re-opening. Please close if you're satisfied.

**Comment by bradchristensen** [comment]
Fantastic! Your fix looks like it should do the trick. Thanks so much for getting on to this so quickly. I'll confirm when I am back in the office on Monday ☺️

**Comment by cressie176** [comment]
> Thanks so much for getting on to this so quickly. 

You did all the hard work. Thanks for your help.

**Comment by bradchristensen** [comment]
Can confirm the fix works perfectly! :smiley: Thanks again.
