### ISSUE TITLE
rascal doesn't provide any information as if its connected correctly or not to rabbitmq

### ISSUE THREAD

**Issue by manodupont** [guidesmiths/rascal#181]
Just a general question that i can't find any doc on that!

When creating a broker, how come if I don't have any rabbitmq cluster running and the conf is pointing to whatever, i don't get any error from rascal !?!?

I don't have a snippet unfortunately but my point is, i am creating a broker and i publish a message. I will receive an error telling me that something went wrong with the publication. But how come rascal is not verbose at all about its "failing" connection at first ?
Is there any way to "healthcheck" the rabbitmq connection  with rascal ?

**Comment by cressie176** [comment]
Hi @manodupont,

Pretty hard to tell without a code snippet, but I suspect you're picking up Rascal's defaults which attempt to connect to localhost on port 5672. Maybe you have RabbitMQ running locally? Maybe you aren't waiting long enough for an connection timeout error?

If you post some sample code I'll take a look. Alternatively if you set the `DEBUG` environment variable to `rascal:*` you'll see exactly what Rascal is attempting to connect to under the hood and whether it is successful.

**Comment by manodupont** [comment]
OK i got it actually. But still i think some improvements on config validation could be made.
my error was

`vhost` instead of `vhosts` in the configuration.

**Comment by manodupont** [comment]
Well, i am still looking to narrow it down. If i take the whole example from the main page on the repo. i do get an EADDRNOTFOUND straight away when trying to connect to this `broker.example.com` broker.

**Comment by cressie176** [comment]
I think it's just that there are 0 vhosts, so Rascal isn't attempting to connect to anything. Agree that's not a legit scenario and happy to add some validation to yield an error if that aren't at least 1.

**Comment by manodupont** [comment]
I think this makes sense. Ill check on that ...

**Comment by cressie176** [comment]
Published as v14.4.0
