### ISSUE TITLE
Streams support?

### ISSUE THREAD

**Issue by dg-eparizzi** [guidesmiths/rascal#187]
Does this library support RabbitMQ Streams over AMPQ 0.9.1? 
If so, are there any examples available? Especially defining the `x-stream-offset` when consuming messages from a Stream.

Thanks

**Comment by cressie176** [comment]
Hi @dg-eparizzi, no - there's no streaming support.

**Comment by dg-eparizzi** [comment]
> Hi @dg-eparizzi, no - there's no streaming support.

I'm not talking about consuming a Stream using the Stream protocol, but just AMQP 0.9.1. According to [official RabbitMQ documentation](https://www.rabbitmq.com/streams.html#usage), Streams can be consumed over AMQP 0.9.1 with very minor changes (apparently, it's just a matter of setting the right arguments on the channel and consumer).

Would it be too hard to add support for it?

**Comment by cressie176** [comment]
Brilliant. Thank you for updating.
