### ISSUE TITLE
Add support for quorum queues

### ISSUE THREAD

**Issue by svrnwnsch** [guidesmiths/rascal#188]
I would be very happy if it could be possible to use  [quorum queues](https://www.rabbitmq.com/quorum-queues.html) in rabbitmq together with rascal.

**Comment by cressie176** [comment]
Hi @svrnwnsch, I believe these should work out of the box. You just need to specify the appropriate queue [arguments](https://github.com/guidesmiths/rascal/blob/master/lib/config/schema.json#L421-L423).

**Comment by svrnwnsch** [comment]
Thank you for the quick response I tried this before and there was some cryptic error. And I therefore assumed this was not supported.

But now it worked with an empty exchange. :tada: 

As a suggestion maybe the README.md could be updated to include a hint to use:
```
              arguments: {
                'x-queue-type': 'quorum',
              },

**Comment by cressie176** [comment]
Hi @svrnwnsch,

README currently has the following

To define a queue with extensions add arguments to the options block

```json
{
  "queues": {
    "q1": {
      "options": {
        "durable": false,
        "arguments": {
          "x-message-ttl": 65000,
          "x-queue-mode": "lazy"
        }
      }
    }
  }
}
```

I don't want to update the readme every time the RabbitMQ team adds another extension, but given how important the quorum queues are, I'lll update to 

To define a queue with extensions such as `x-queue-type` etc. add arguments to the options block, e.g.

At least that way a search of the README should find it. Make sense?
