### ISSUE TITLE
Question about busy publisher example

### ISSUE THREAD

**Issue by carlosvillademor** [guidesmiths/rascal#194]
Hello @cressie176, once again, thanks for the amazing library, whenever we need something, there it is Rascal to the rescue! I have a question regarding the example configuration you have for the busy publisher on https://github.com/guidesmiths/rascal/tree/master/examples/busy-publisher. 

You use non baseline configuration for the `confirmPool` to increase, among other changes, the min and max value of the pool. But in the only publication you have, you set `"confirm": false`. As described on https://github.com/guidesmiths/rascal/blob/master/README.md#channel-pooling, you use two different pools.  And I understand there that the confirmPool is used by the publications where the confirm is set to true. So in the busy publisher example, my understanding is that the `demo_pub` publication would be using the regularPool, as it has `"confirm":false`, but the settings to increase the min and max are done for the `confirmPool`. 

So, am I misunderstanding something? Or should you be changing the min and max for the `regularPool` instead?

Thanks in advance for your time @cressie176 looking into this, and I hope you are doing well mate.

**Comment by cressie176** [comment]
Hi @carlosvillademor,

Good spot, I'll update the example.

All well here, hope the same for you.

**Comment by carlosvillademor** [comment]
Thanks @cressie176 , everything ok here, thanks.
