### ISSUE TITLE
SubscribeAll behaviour

### ISSUE THREAD

**Issue by torohaifisch** [guidesmiths/rascal#196]
hello, i wanted to ask about this methods behaviour. when i use it, it subscribes to all the defined subscriptions in my config.json but also is subscribing to all the defined queues too, is this the intended behaviour? because from the documentation i understand that this method should only subscribe to the defined subscriptions and not the queues.

**Comment by cressie176** [comment]
Hi @torohaifisch,

broker.subscribeAll subscribes to **all** subscriptions by default, including the ones that are automatically created for each of the queues. If you want to exclude these, then you can specify a filter. You'll find an example in the [README](https://github.com/guidesmiths/rascal#subscribe-all)
