### ISSUE TITLE
Dependency on amqplib

### ISSUE THREAD

**Issue by gsuhm** [guidesmiths/rascal#197]
Love Rascal, but amqplib seems to be going through some tough times - 

[Is amqplib abandoned?](https://github.com/amqp-node/amqplib/issues/679)
[amqplib full issue list](https://github.com/amqp-node/amqplib/issues) - 130 open issues!

Any thoughts on the future of Rascal using amqplib?

**Comment by cressie176** [comment]
Hi @gsuhm,

I've no plans to migrate Rascal to another client. While I agree the current situation with amqplib isn't ideal, nothing else comes close to its reliability or maturity. I'm also not sure that the level of concern raised by some users is fully justified. For example, the vulnerability with url-parse is highly unlikely to affect users, unless an untrusted party has access to the connection configuration.
