### ISSUE TITLE
LoggableUrl Leaks partial passwords

### ISSUE THREAD

**Issue by matt1097** [guidesmiths/rascal#200]
The Regex for loggableUrl can leak passwords if the password has a @ in it.
Here:  https://github.com/guidesmiths/rascal/blob/2dbe72abce8386eee8762e421ed4b49fbee0c5fc/lib/config/configure.js#L88

This regex matches the first @ found, when it needs to match the last @ found.

For example if the password was "badp@ssword", the log would log: `http://user:***@ssword@url` instead of the expected `http://user:***@url`

![image](https://user-images.githubusercontent.com/48395861/173481996-c4d455ee-fc1d-439e-918c-e870c2b1bf3b.png)

**Comment by cressie176** [comment]
Thanks @matt1097, will resolve

**Comment by cressie176** [comment]
Fixed in rascal@v14.4.5

**Comment by cressie176** [comment]
Something strange with the tag. Double checking the fix was published

**Comment by cressie176** [comment]
Yep, all good. Thanks again for reporting
