### ISSUE TITLE
Error "Vhost: myvhost refers to an unsupported attribute: encryption"

### ISSUE THREAD

**Issue by mchristensen76** [guidesmiths/rascal#30]
I used the settings from the documentation here: https://github.com/guidesmiths/rascal#encrypting-messages

When I add the `encryption` field to the vhost I get this error:

`Error "Vhost: myvhost refers to an unsupported attribute: encryption`.  If I remove the encryption field it works as expected.

This setting does not work:

```
"publications": {
    "my_q": {
        "queue": "my.q",
        "encryption": "well-known-v1"
    }
},
"encryption": {
    "well-known-v1": {
        "key": "f81db52a3b2c717fe65d9a3b7dd04d2a08793e1a28e3083db3ea08db56e7c315",
        "ivLength": 16,
        "algorithm": "aes-256-cbc"
    }
}
```

I saw the test's added it to the publication field, if I add it there and remove it from the vhost it works fine.  This setting works:
```
my_q: {
    queue: `my_q`,
    encryption: {
        name: 'well-known',
        key: 'f81db52a3b2c717fe65d9a3b7dd04d2a08793e1a28e3083db3ea08db56e7c315',
        ivLength: 16,
        algorithm: 'aes-256-cbc',
    }
}
```

Any ideas?  I'm using "version": "3.2.0".

**Comment by cressie176** [comment]
The encryption config needs to be outside the vhosts configuration. i.e.
```
{
  vhosts: { },
  encryption: {}
}
```

What's probably caused the confusion is that publications, can be inside or outside the vhost configuration, so when the examples do

```
{
  publication: {}
  encryption: {}
}
```
it is correct, but not if your configuration is
```
{
   vhosts: {
     "/": {
       publications: {}
       encryption: {}
     }
  }
}
```
I'll try and make the readme clearer.

**Comment by cressie176** [comment]
I've updated the readme and advanced example.

**Comment by mchristensen76** [comment]
I made the changes and its working now, thx!
