### ISSUE TITLE
"Encryption: name refers to an unsupported attribute: 0" when setting encryption field in subscription to a profile name

### ISSUE THREAD

**Issue by mchristensen76** [guidesmiths/rascal#31]
Here's the setting:

```
"s1": {
    queue: `q1`,
    encryption: "well-known",
    contentType: "application/json",
    redeliveries: {
        limit: 5,
        counter: "shared"
    }
}
```

The readme doesn't show an example under the subscription section.  There is a section for it but the example seems incomplete.

If I comment out the `encryption` field it works.

Outside of the `vhost` section I have this setting:

```
"well-known": {
    key: this.cryptoKey,
    ivLength: 16,
    algorithm: "aes-256-cbc"
}
```

**Comment by cressie176** [comment]
You don't need to specify the encryption profile name in the subscription config. It's detected automatically by a message header

**Comment by mchristensen76** [comment]
Thx.  I got it working.
