### ISSUE TITLE
Why callback of the subscription 'error' event doesn't have 'ackOrNack' parameter as 'message' and 'invalid_content' ?

### ISSUE THREAD

**Issue by PaoloLaurenti** [guidesmiths/rascal#40]
I don't understand the reason why the callback of the subscription _error_ event doesn't have `ackOrNack` parameter.
In this way, if I want to handle a recovery strategy in case of an unhandled error inside the _message_ event handler, I need to catch the error. Therefore I don't understand what is the purpose of the _error_ event...

I was expecting that in case of an unhandled error inside the _message_ event handler, Rascal would emit the _error_ event passing the `ackOrNack`  callback as parameter. So, in this case, inside the _error_ event handler I could fire-up my recovery strategy (without the need to catch anything inside the _message_ event handler).

**Comment by cressie176** [comment]
Hi @PaoloLaurenti,

The subscription error event handler is to let you know about connection errors or channel errors. These original from the underlying amqplib library. Rascal will handle them by re-establishing a connection and re-subscribing to the channel, but they can indicate problems with your application (e.g. you've acknowledged a message twice) so rascal re-emits the error.

**Comment by PaoloLaurenti** [comment]
Hi @cressie176 ,
thank you very much for your prompt reply.
I get you point but I think that there is still something that is strange to me: if an unhandled error happens inside the _message_ event handler, the error will be notified by the _error_ event (probably because it will result in a channel error...). I tried this and this is the reason why I started wondering why the error event has been designed in this way. So, somehow, the unhandled errors inside the _message_ event handler are already catched...
Therefore: it wouldn't be better to pass the `ackOrNack` callback as parameter of the _error_ event handler avoiding the library user to handle manually the errors catching inside the _message_ event handler in order to fire-up its own recovery strategy?

**Comment by cressie176** [comment]
Hi,
It’s still not Rascals responsibility to handle programming errors, and not possible to catch errors in all cases. If the error happens after the handler had acknowledged the message then passing the ackOrNack function to the error handler would only add to the confusion

**Comment by PaoloLaurenti** [comment]
> If the error happens after the handler had acknowledged the message then passing the ackOrNack function to the error handler would only add to the confusion

OK, now I understand.
Sorry if I bothered you and thank again for your time.

Paolo

**Comment by cressie176** [comment]
No bother. Always happy to take questions.
