### ISSUE TITLE
Support connection max retries 

### ISSUE THREAD

**Issue by ricardobcl** [guidesmiths/rascal#42]
Hi there,

What do you think about supporting an additional flag `maxRetries` inside `connection.retry` config?

Without a max retries, there is a change that the app is stuck in a loop reconnecting when there's something wrong externally.

With max retries, eventually the app would exit/crash and it would be easier to see that something is wrong.

**Comment by cressie176** [comment]
I think that's a good suggestion, although I would probably call it `attempts`, and default to zero for infinite.

```js
{
  "vhosts": {
    "v1": {
      "connection": {
        "retry": {
          "attempts": 100,
          "min": 1000,
          "max": 60000,
          "factor": 2,
          "strategy": "exponential"
        }
      }
    }
  }
}
```

It's a shame I called the interval properties just "min" and "max" :(

**Comment by cressie176** [comment]
I'm going to close this - it's not something I've found time to get around to, plus it should be easy to hook in to the broker.error event and report repeated disconnections, or gracefully shutdown the application after a specific number of applications.
