### ISSUE TITLE
Change Delay Queue's TTL

### ISSUE THREAD

**Issue by SamiSammour** [guidesmiths/rascal#46]
In my setup I have multiple queues with various delays and these delays are configurable, so as I made some search if I want to change any config of a queue I need to create a new queue then migrate messages in the old queue to the new one and then delete the old one. I tried to find something to help me achieve this with `rascal` but couldn't find anything to help me delete a queue/exchange/binding from the exposed API.  
I really liked this tool and I'm thinking of using it in my app instead of the `amqplib` because of the reasons mentioned here.

So do you have any suggestion on how I might do this?

**Comment by cressie176** [comment]
Hi @SamiSammour,

Deleting / recreating queues can be a real pain, especially in a system that's already live. The best approach is context specific. 

### Approach 1
1. Set up the new queue config, bound with a different routing key
1. Consume from both new and old queues
1. Update the publisher to route messages to the new queue. 
1. After the original queue was drained and messages started arriving on the new one, delete the original queue.

However this only works if you have control of the publisher and can tolerate out of order messages.

### Approach 2
1. Pause the publisher
2. Drain the original queue
3. Delete and re-create it with the new configuration.

However this only works if you have control of the publisher and can afford to pause messages

### Approach 3
1. Create the new another queue
2. Route messages to both
3. Once you sure you've processed all messages from the original queue simply delete it.

However this requires you to be able to tolerate duplicates. I'm sure there are more approaches, but I've never found one that isn't a faff.

**Comment by SamiSammour** [comment]
Thank you @cressie176 for your quick response.  
But does `rascal` have management APIs? or shall I use `amqplib`? and if I do.. I couldn't find any way to update the config of the broker!

**Comment by cressie176** [comment]
No. There's nothing in rascal that lets you delete a queue (other thank broker.nuke which is intended to teardown all configured queues and exchanges for testing purposes). One of the things I've been thinking about is adding a feature where you can programatically connect from rascal using a named connection configuration. This would expose the majority of the amqplib API directly. Something like
```
const connection = await broker.connect(connectionName)
```
or
```
broker.connect(connectionName, (err, connection) => { }
```
Would this make things easier?

**Comment by SamiSammour** [comment]
I was thinking of using the `shutdown` method then creating a new broker with new config. isn't that the same thing?

**Comment by cressie176** [comment]
`shutdown` unsubscribes all consumers and disconnects all vhosts, but it wouldn't delete the old queues or unbind them from exchanges. With the connect method you would be able to do something like...

```js
await broker.shutdown();
const connection = await broker.connect('/');
const channel = await connection.createChannel();
await channel.delete('oldQueue');
await channel.close();
await connection.close();
broker.create(newConfig);
```

**Comment by SamiSammour** [comment]
I'm sorry I wasn't clear enough in my previous response, I'm aware that `shutdown` wouldn't delete old queues, I would rather use the `deleteQueue` method directly from `amqplib` to do so, but if you can wrap it with `connect` method that would be great I think.

**Comment by cressie176** [comment]
broker.connect added in rascal@3.4.0 
FYI I also moved amqplib to a peer dependency.

**Comment by SamiSammour** [comment]
that's great thanks.. but why did you move `ampqlib` to peer dependencies? I didn't get the reason!

**Comment by cressie176** [comment]
It wasn't related to this issue. The reason is so users can independently update amqplib to a later compatible release without waiting for me to release a new version of rascal.

**Comment by SamiSammour** [comment]
I'm not sure if this is related to this new update but I'm getting this error while trying to run the advanced example:
```
node index.js 
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
process.send is not a function
Deleting user: Louise_Garuglieri
/home/sami/Documents/AlphaApps/Development/rabbitmq-compose-master/node_modules/rascal/examples/advanced/handlers/deleteUser.js:11
            if (user.crash) throw new Error('Crashing on user: ' + user.username)
                            ^

Error: Crashing on user: Louise_Garuglieri
    at Immediate.<anonymous> (/home/sami/Documents/AlphaApps/Development/rabbitmq-compose-master/node_modules/rascal/examples/advanced/handlers/deleteUser.js:11:35)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by cressie176** [comment]
Sorry, I should have been more clear...

```process.send is not a function```

Is probably because you're running `node index` rather than `node cluster`. The advanced example uses a [cluster](https://nodejs.org/api/cluster.html) based redelivery counter to guard against poison messages.

```
Error: Crashing on user: Louise_Garuglieri
    at Immediate.<anonymous> (/home/sami/Documents/AlphaApps/Development/rabbitmq-compose-master/node_modules/rascal/examples/advanced/handlers/deleteUser.js:11:35)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Is simulating a poison message - a corrupt message which cannot be handled by the application. In this case I'm simulating something that actually crashes the node process, causing the message to be rolled back to the queue. If it wasn't for the redelivery counter the message would be redelivered indefinitely, causing the node process to continually crash.

**Comment by cressie176** [comment]
@SamiSammour OK to close?

**Comment by SamiSammour** [comment]
Hey @cressie176, I was wondering if I can access the connection instance from the broker instance. I'm quite new to RabbitMQ and I've just read about the `x-expires` argument that can be set for the queue that will cause the queue to be deleted after some period of time of inactivity, so what I was thinking is I just set an expiry time for my delayed queue and like this I don't bother deleting the queue after changing the config. So in consequence to this I have to assert the queue before every publication to ensure it is not deleted due to inactivity.

**Comment by cressie176** [comment]
Hi @SamiSammour, no you can't access the connection instance from the broker instance. I don't think that would be a good idea - Rascal adds error handlers to the connection, and will reconnect if there's a problem. If the library were to expose the connection, there would be no way to ensure it wasn't broken.

Re the multiple delay queues - what we do is create a range of permanent delay queues, e.g.

* delay.1s
* delay.1m
* delay.5m
* delay.10m

And route messages to the appropriate one using a CC routing key (delay.1s for example). Is there a reason why the delay needs to be configurable or would having a finite number of queues do?

**Comment by SamiSammour** [comment]
The delay is bound to some business logic requirement. The client wants to configure the delays from the web dashboard and I'm not sure what values he might use. So now I will come to the following setup in my env:

1. I'll have a default settings for the delays and I'll read them on app start the first time and configure the broker with it.
2. Whenever the config is changed I'll update the broker with the new config only without deleting old queues so I don't lose any messages in it, and I'll store these config so the right config is loaded on app restarts.
3. I can live with inactive queues as the config change is not frequent at all, but I'm thinking of creating a job to clean those unused queues.

Thank you a lot @cressie176 in helping me on this issue, your comments were very helpful.  
I'll close this issue now as it's resolved.
