### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [guidesmiths/rascal#49]
Are there any TypeScript type definitions (https://github.com/DefinitelyTyped/DefinitelyTyped) available for this? If not, does anyone have any custom types they are using?

**Comment by cressie176** [comment]
Hi @jacobcabantomski-ct,

I'm aware of TypeScript but never used it, so not going to be able to help much on this one. Based on my limited experience of [Flow](https://reactjs.org/docs/static-type-checking.html) I also wonder how viable/useful/enjoyable TypeScript would be with Rascal. 

* Many of the functions support a variable number of parameters. e.g. [publish](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Broker.js#L121-L127)

* Some of the options are passed directly to amqplib, which I suspect would create a TypeScript dependency between the two, e.g. [connect](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/tasks/createConnection.js#L35)

* The 'message' event rascal emits includes both amqplib's representation of the RabbitMQ raw message (another dependency) and the parsed content, which could be any content type. See [emit('message')](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Subscription.js#L67)

* The messages the user publishes can also be any content type. See [getContent](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Publication.js#L99-L103)

My TypeScript experience is almost zero, so I'm happy to be schooled to the contrary.

**Comment by jacobcabantomski-ct** [comment]
@cressie176 Agreed, there are a number of modalities/params for those methods and handlers, so typing on certain fields might have to be loose/mixed or not valuable at all.

`amqplib` has type definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/amqplib which have been helpful thus far with some initial functionality we have built out.

**Comment by jacobcabantomski-ct** [comment]
I ended up writing a custom types file for our specific usage of `rascal` with async/await:

`./src/@types/rascal/index.d.ts`
```typescript
declare module "rascal" {
	import {EventEmitter} from "events";

 	export function withDefaultConfig(config: object): object;

 	export interface IConfig {
		recovery?: object;
	}

 	interface IPublishOptions {
		routingKey: string;
		options: {
			correlationId: string;
		};
	}

 	// tslint:disable-next-line:interface-name
	export interface Broker extends EventEmitter {
		config: IConfig;

 		subscribe(subscription: string): Promise<EventEmitter>;
		publish(publication: string, content: any, options: IPublishOptions): Promise<EventEmitter>;

 		shutdown(callback?: () => void): void;
	}

 	export class BrokerAsPromised {
		public static create(config: object, extras?: { counters: object }): Promise<Broker>;
	}
}
```

After writing this and per your message above, was difficult handling all the different possible input and return types so made this specific usage.

**Comment by jacobcabantomski-ct** [comment]
Also wanted to give props for the excellent documentation and examples (especially the advanced one) in this repo, as well as the `redis` add-on (https://github.com/cressie176/rascal-redis-counter). They were all able to meet our needs for integrating with RabbitMQ and made the process much easier. Thanks!

**Comment by cressie176** [comment]
> was difficult handling all the different possible input and return types so made this specific usage.

In retrospect passing in an object might have been a better choice than the variadic function.

> Also wanted to give props for the excellent documentation and examples (especially the advanced one) in this repo, as well as the redis add-on

👍 Glad you found them useful

**Comment by SamiSammour** [comment]
To anyone who's looking for typings to this lib there's a [package](https://www.npmjs.com/package/@types/rascal) for that
