### ISSUE TITLE
Setup mirrored queues

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [guidesmiths/rascal#53]
Hi,

Is there a way via the Rascal's config we could setup [mirrored queues](https://www.rabbitmq.com/ha.html#replication-factor)?

**Comment by cressie176** [comment]
Hi @jacobcabantomski-ct 

No Rascal is *mostly* a wrapper for amqplib, so you're limited to features of amqp 0.9.1. The one exception to this is the ability to automatically create VHOSTS using the HTTP protocol, but this isn't intended to be a production feature, it's just to support testing.

**Comment by jacobcabantomski-ct** [comment]
Thanks @cressie176 , I'll take a look into some other ways to configure that setup.
