### ISSUE TITLE
amqplib missing dependency

### ISSUE THREAD

**Issue by UlisesGascon** [guidesmiths/rascal#57]
Hi team!

I got an error  `Error: Cannot find module 'amqplib/callback_api'` just after requiring the module.

**Sample code to test:**
```js
const Rascal = require('rascal')
console.log("Hi Rascal!")
```

**I am using:**
- Node v10.15.3
- NPM v6.9.0
- OSX 10.14
- Rascal 4.5.0

**Versions affected**
- `v4.3.0`
- `v4.4.0`
- `v4.5.0`

**Why?**
I discovered that in version v4.3.0 [the dependecies were modified](https://github.com/guidesmiths/rascal/commit/a24fdb932f012d4c722cdcb8b7382555923b8482#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L7). So `amqplib` is part of `devDependencies` and `peerDependencies`. But since Npm@3, the way to manage peer dependencies has changed. So it won't install it by default (as expected).
- [NPM@3 Changelog](https://github.com/npm/npm/releases/tag/v3.0.0)
- [NPM@3 Announce](https://blog.npmjs.org/post/110924823920/npm-weekly-5)

**How to fix it?**
I was able to fix this bug. In order to do that I relocated `amqplib` as regular dependency and not `devDependencies`.

Please confirm if you believe that this is the correct way to fix it.

I will open a PR asap :wink:

**Comment by cressie176** [comment]
Hi @UlisesGascon,

Thanks for the raising the issue. I deliberately moved the amqplib dependency to a peer dependency with the intention of making it easier to update. Otherwise simply going `npm i rascal@latest' won't cause latest versions of amqplib to be installed.

**Comment by manodupont** [comment]
Sorry for disturbing but I do have the same problem with the latest rascal !?

I am using `"rascal": "^13.1.3",`

**The error**
```
Debugger attached.
Error: Cannot find module 'amqplib/callback_api'
Require stack:
- /Users/manuel/connector-job-scheduler/node_modules/rascal/lib/amqp/tasks/createConnection.js
- /Users/manuel/connector-job-scheduler/node_modules/rascal/lib/amqp/tasks/index.js
- /Users/manuel/connector-job-scheduler/node_modules/rascal/lib/amqp/Broker.js
- /Users/manuel/connector-job-scheduler/node_modules/rascal/index.js
```

The devDependency showing in rascal module
```
{
  "_from": "rascal",
  "_id": "rascal@13.1.3",
  "_inBundle": false,
  "_integrity": "sha512-5iE2y4MGGTg0AuXVL+M3euzCC+fK6yrQbK7xiIerwtuOeXXNd7K8tZy2fFZid4LaD0xUEIQJ1V6ZkAc8PgCh9w==",
  "_location": "/rascal",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "rascal",
    "name": "rascal",
    "escapedName": "rascal",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER",
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/rascal/-/rascal-13.1.3.tgz",
  "_shasum": "79e1f1f5f703adfbd540c11f32d5bbebe0a0c4c2",
  "_spec": "rascal",
  "_where": "/Users/manuel/connector-job-scheduler",
  "author": {
    "name": "Stephen Cresswell"
  },
  "bugs": {
    "url": "https://github.com/guidesmiths/rascal/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "async": "^3.2.1",
    "debug": "^4.1.1",
    "deep-freeze": "0.0.1",
    "forward-emitter": "^0.1.1",
    "generic-pool": "^3.7.1",
    "lodash": "^4.17.21",
    "lru-cache": "^6.0.0",
    "safe-json-parse": "^4.0.0",
    "stashback": "^1.1.2",
    "superagent": "^6.1.0",
    "uuid": "^8.3.2",
    "xregexp": "^5.0.1"
  },
  "deprecated": false,
  "description": "A config driven wrapper for amqplib supporting multi-host connections, automatic error recovery, redelivery flood protection, transparent encryption / decryption,  channel pooling and publication timeouts",
  "devDependencies": {
    "amqplib": "^0.8.0",
    "chalk": "^4.0.0",
```


Whats the fix for that except installing ampqlib by myself ?

Thanks

**Comment by cressie176** [comment]
That is the fix, amqplib is a peer dependency and you have to explicitly install it.

**Comment by manodupont** [comment]
Oh. Ok great. No problem with that then.

Thanks a lot for the quick reply.
