### ISSUE TITLE
How/where to handle Heartbeat timeout exception

### ISSUE THREAD

**Issue by carlosvillademor** [guidesmiths/rascal#59]
Hi @cressie176,

I am trying to test the reconnection part of Rascal. When shutting down RabbitMQ, I see the reconnection code working, using the DEBUG mode for Rascal. I see some instances of Heartbet timeout coming up from the amqplib, like:

```at Heart.emit (events.js:198:13)',\n     '    at Heart.EventEmitter.emit (domain.js:448:20)',\n     '    at Heart.runHeartbeat (/Users/carlosgarcia/Documents/mailonline/development/mol-fe/mol-fe-web-push-api/node_modules/amqplib/lib/heartbeat.js:88:17)',\n     '    at ontimeout (timers.js:436:11)',\n     '    at tryOnTimeout (timers.js:300:5)',\n     '    at listOnTimeout (timers.js:263:5)',\n     '    at Timer.processTimers (timers.js:223:10)' ]```

I have two applications, one producer and one consumer, using the same broker, and while the producer is able to publish messages after the reconnection, the consumer is not able to consume messages even though it seems that is has reconnected and re-established the subscriptions.

I see uncaught exceptions for the hearbeat and unexpected close errors. How should I handle those? I have .on('error') listeners in all the places mentioned in the documentation, when creating the broker and for the subscription and the publication. We use the promise version.

I can see this in the DEBUG rascal logs on the consumer application 

`rascal:Vhost Initialising vhost: my-host-name
rascal:tasks:createConnection Connecting to broker using url: amqp://admin:***@localhost:5673/web-push-api?heartbeat=10&connection_timeout=10000&channelMax=100
rascal:tasks:createConnection Obtained connection: my-connection-hash
rascal:tasks:createChannel Creating channel
rascal:tasks:assertExchanges Asserting exchange: my-exchange
rascal:tasks:assertQueues Asserting queue: subscription
rascal:tasks:applyBindings Binding queue: subscription to exchange: my-exchange with binding key: my-binding-key
rascal:tasks:closeChannel Closing channel
rascal:Vhost vhost: my-host-name was initialised with connection: my-connection-hash`

Is normal that it closes the channel?

Checking the RabbitMQ UI Management, it seems the consumer doesn't get attached to the queue.

Please, let me know if you need any more info from my side.

Thanks a lot.

**Comment by cressie176** [comment]
Hi @carlosvillademor,

Nice to hear from you. The channel that's being closed is the one rascal used to assert the exchanges and queues. It is normal for rascal to close this after initialising the vhost. You can see the series of tasks [here](https://github.com/guidesmiths/rascal/blob/master/lib/amqp/Vhost.js#L30)

It's odd that you're seeing uncaught exceptions though. I've no explanation for that, and don't get them if I run the simple example and pause the docker container after a while, e.g.

```
npm run docker
cd examples/simple
DEBUG='rascal:*' node index.js 
```

2019-07-03T21:07:11.924Z: hello world
  rascal:SubscriberSession Acknowledging message: 4b53bcba-e6b2-4aad-8ba9-b952d7cd3dc6 on channel: 5458fdcf-ed24-4507-80d4-84d370f2c3f3 +1s
  rascal:Vhost Returning confirm channel: d5473513-8be8-436e-8c97-c4ad2825fe1a. Queue size: 0, pool size: 1, available: 0, taken: 1 +11ms
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 1, taken: 0 +993ms
  rascal:Vhost Borrowed confirm channel: d5473513-8be8-436e-8c97-c4ad2825fe1a. Queue size: 0, pool size: 1, available: 0, taken: 1 +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +1s
  rascal:Subscription Received message: f3747b34-eaed-4b6c-9360-3770b85d839e from queue: demo_q +1s
2019-07-03T21:07:12.928Z: hello world
  rascal:SubscriberSession Acknowledging message: f3747b34-eaed-4b6c-9360-3770b85d839e on channel: 5458fdcf-ed24-4507-80d4-84d370f2c3f3 +1s
  rascal:Vhost Returning confirm channel: d5473513-8be8-436e-8c97-c4ad2825fe1a. Queue size: 0, pool size: 1, available: 0, taken: 1 +14ms
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 1, taken: 0 +991ms
  rascal:Vhost Borrowed confirm channel: d5473513-8be8-436e-8c97-c4ad2825fe1a. Queue size: 0, pool size: 1, available: 0, taken: 1 +0ms
```
```
docker pause rascal-rabbitmq
```
```
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +1s
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 1, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 0, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 1, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 2, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 3, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 4, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 5, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 6, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 7, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 8, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 9, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 10, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 11, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 12, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 13, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 14, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 15, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 16, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 17, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 18, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 19, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 20, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Requested confirm channel. Queue size: 21, pool size: 1, available: 0, taken: 1 +1s
  rascal:Vhost Handling connection error: Heartbeat timeout initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +851ms
Error: Heartbeat timeout
    at Heart.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:427:19)
    at emitNone (events.js:106:13)
    at Heart.emit (events.js:208:7)
    at Heart.runHeartbeat (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/heartbeat.js:88:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Vhost Initialising vhost: / +1ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +40s
  rascal:Subscription Handling channel error: Heartbeat timeout from demo_sub using channel: 5458fdcf-ed24-4507-80d4-84d370f2c3f3 +25s
Error: Heartbeat timeout
    at Heart.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:427:19)
    at emitNone (events.js:106:13)
    at Heart.emit (events.js:208:7)
    at Heart.runHeartbeat (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/heartbeat.js:88:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Publication Channel error: Heartbeat timeout during publication of message: 886cdac7-8302-4c34-8311-1f17ad7dcd6b to demo_pub using channel: d5473513-8be8-436e-8c97-c4ad2825fe1a +24s
Error: Heartbeat timeout
    at Heart.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connection.js:427:19)
    at emitNone (events.js:106:13)
    at Heart.emit (events.js:208:7)
    at Heart.runHeartbeat (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/heartbeat.js:88:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5) '886cdac7-8302-4c34-8311-1f17ad7dcd6b'
  rascal:SubscriberSession Removing channel: 5458fdcf-ed24-4507-80d4-84d370f2c3f3 from session +25s
  rascal:Subscription Subscribing to queue: demo_q +2ms
  rascal:Vhost Requested channel. Outstanding channel requests: 2 +4ms
  rascal:Vhost Requested confirm channel. Queue size: 22, pool size: 1, available: 0, taken: 0 +149ms
  rascal:Vhost Will attempt reconnection in in 1392ms +853ms
  rascal:Vhost Requested confirm channel. Queue size: 23, pool size: 1, available: 0, taken: 0 +151ms
  rascal:Vhost Requested confirm channel. Queue size: 24, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +232ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connect.js:172:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Vhost Initialising vhost: / +2ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +2s
  rascal:Vhost Requested confirm channel. Queue size: 25, pool size: 1, available: 0, taken: 0 +771ms
  rascal:Vhost Will attempt reconnection in in 3848ms +233ms
  rascal:Vhost Requested confirm channel. Queue size: 26, pool size: 1, available: 0, taken: 0 +772ms
  rascal:Vhost Requested confirm channel. Queue size: 27, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 28, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 29, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +68ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connect.js:172:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +5s
  rascal:Vhost Requested confirm channel. Queue size: 30, pool size: 1, available: 0, taken: 0 +936ms
  rascal:Vhost Will attempt reconnection in in 6215ms +67ms
  rascal:Vhost Requested confirm channel. Queue size: 31, pool size: 1, available: 0, taken: 0 +937ms
  rascal:Vhost Requested confirm channel. Queue size: 32, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 33, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 34, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 35, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 36, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +263ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connect.js:172:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +7s
  rascal:Vhost Requested confirm channel. Queue size: 37, pool size: 1, available: 0, taken: 0 +738ms
  rascal:Vhost Will attempt reconnection in in 11174ms +267ms
  rascal:Vhost Requested confirm channel. Queue size: 38, pool size: 1, available: 0, taken: 0 +734ms
  rascal:Vhost Requested confirm channel. Queue size: 39, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 40, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 41, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 42, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 43, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 44, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 45, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 46, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 47, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 48, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +401ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connect.js:172:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  rascal:Vhost Initialising vhost: / +0ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +12s
  rascal:Vhost Requested confirm channel. Queue size: 49, pool size: 1, available: 0, taken: 0 +603ms
  rascal:Vhost Will attempt reconnection in in 22491ms +402ms
  rascal:Vhost Requested confirm channel. Queue size: 50, pool size: 1, available: 0, taken: 0 +600ms
  rascal:Vhost Requested confirm channel. Queue size: 51, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 52, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 53, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 54, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 55, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 56, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 57, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 58, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 59, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 60, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 61, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 62, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 63, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 64, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 65, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 66, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 67, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 68, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 69, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 70, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Requested confirm channel. Queue size: 71, pool size: 1, available: 0, taken: 0 +1s
  rascal:Vhost Handling connection error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT initially from connection: 9a7be731-b9c3-400b-9dbd-d0a56d8bdd68, vhost:amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +814ms
Error: Failed to connect to: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100. Original message was: connect ETIMEDOUT
    at Socket.<anonymous> (/Users/steve/Development/guidesmiths/rascal/node_modules/amqplib/lib/connect.js:172:20)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

```
docker unpause rascal-rabbitmq
```
```
  rascal:Vhost Initialising vhost: / +1ms
  rascal:tasks:createConnection Connecting to broker using url: amqp://guest:***@localhost:5672?heartbeat=10&connection_timeout=10000&channelMax=100 +24s
  rascal:tasks:createConnection Obtained connection: 14ab05a0-ef7b-46fd-8ef9-49b8779f015e +11ms
  rascal:tasks:createChannel Creating channel +2m
  rascal:tasks:assertExchanges Asserting exchange: demo_ex +2m
  rascal:tasks:assertQueues Asserting queue: demo_q +2m
  rascal:tasks:applyBindings Binding queue: demo_q to exchange: demo_ex with binding key: a.b.c +2m
  rascal:tasks:closeChannel Closing channel +2m
  rascal:Vhost vhost: / was initialised with connection: 14ab05a0-ef7b-46fd-8ef9-49b8779f015e +23ms
  rascal:Vhost Created channel 90ac8002-7370-441c-956f-425710cbc791 from connection: 14ab05a0-ef7b-46fd-8ef9-49b8779f015e +16ms
  rascal:Vhost Borrowed confirm channel: 90ac8002-7370-441c-956f-425710cbc791. Queue size: 72, pool size: 1, available: 0, taken: 1 +1ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +50s
  rascal:Vhost Created channel e91b1968-13e2-4b80-a0ca-3418af5e15b7 from connection: 14ab05a0-ef7b-46fd-8ef9-49b8779f015e +6ms
  rascal:Vhost Returning confirm channel: 90ac8002-7370-441c-956f-425710cbc791. Queue size: 71, pool size: 1, available: 0, taken: 1 +7ms
  rascal:Vhost Borrowed confirm channel: 90ac8002-7370-441c-956f-425710cbc791. Queue size: 71, pool size: 1, available: 0, taken: 1 +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +13ms
  rascal:SubscriberSession Opening subscriber session: amq.ctag-3ujqH7hOkOy1m8dr_qaBaA on channel: e91b1968-13e2-4b80-a0ca-3418af5e15b7 +50s
  rascal:Subscription Received message: ccb48b46-3c83-4c49-99c8-e8f3e2bbebb7 from queue: demo_q +50s
2019-07-03T21:07:14.937Z: hello world
  rascal:SubscriberSession Acknowledging message: ccb48b46-3c83-4c49-99c8-e8f3e2bbebb7 on channel: e91b1968-13e2-4b80-a0ca-3418af5e15b7 +1ms
  rascal:Subscription Received message: 8e340e30-2cb4-4efd-bec4-f95202bf75e3 from queue: demo_q +3ms
2019-07-03T21:07:15.939Z: hello world
  rascal:SubscriberSession Acknowledging message: 8e340e30-2cb4-4efd-bec4-f95202bf75e3 on channel: e91b1968-13e2-4b80-a0ca-3418af5e15b7 +3ms
  rascal:Vhost Returning confirm channel: 90ac8002-7370-441c-956f-425710cbc791. Queue size: 70, pool size: 1, available: 0, taken: 1 +7ms
  rascal:Vhost Borrowed confirm channel: 90ac8002-7370-441c-956f-425710cbc791. Queue size: 70, pool size: 1, available: 0, taken: 1 +0ms
  rascal:Publication Publishing 37 bytes to confirm exchange: demo_ex with routingKeys: a.b.c +7ms
  rascal:Subscription Received message: 202e046f-5f98-498b-afc2-6b295974677d from queue: demo_q +6ms
2019-07-03T21:07:16.941Z: hello world
```

**Comment by cressie176** [comment]
@carlosvillademor any luck?

**Comment by carlosvillademor** [comment]
Hey @cressie176,

very sorry for the late reply mate. Well, kind of. It got better when I changed to use only one broker per application. I was using two at the beginning. My reasoning being to have two different TCP connections, one for subscriptions and another for publications. Later I realised that was done under the hood by Rascal. The fact is that I was able to see the reconnection happening although sometimes my application dies, but it has nothing to do with Rascal. I have a listener on the process exit event, but it is not giving much information about why is exiting. Anyway, nothing to do with Rascal.

So sorry for the false alarm, and thanks for the help. Maybe we could add explicitly that Rascal creates two different TCP connections under the hood to the documentation, what do you think? I was reading best practices on CloudAMQP and they talk about the two connections to separate publishers and consumers, hence my try to create two brokers, if you see what I mean.

Thanks @cressie176! And nice job this Rascal!

**Comment by cressie176** [comment]
Hi @carlosvillademor, I don't think Rascal does create multiple connections - it will create multiple channels though.

**Comment by wolfejw86** [comment]
Just thought it was worth mentioning, I am not doing anything but the boilerplate examples in an application and have seen the heartbeat timeout error boil up and crash my app sporadically. I haven't been able to pinpoint why sometimes it does and sometimes it doesn't.  I attach the error handlers in the 4 places it says to in the documentation, and even see the error message get logged, but it somehow still bubbles up to the top scope and crashes the app.  I will try to reproduce in an isolated docker setting with my exact configuration.
