### ISSUE TITLE
Dynamic assertion of queues and exchanges. 

### ISSUE THREAD

**Issue by Ibrahimtrrc** [guidesmiths/rascal#63]
I didn't find the way to access the amqplib functions like "assertQueue" or "bindQueue" to dynamically add some exchanges, queues, etc on the configuration.

for my needs as an example , i want to publish on new exchanges that i create dynamically depending on the different parameters that i receive on my API

( Thanks a lot for this library ;) )
using : 
rascal : 4.6.2
node : 10.15.3

**Comment by cressie176** [comment]
Hi @Ibrahimtrrc,

There's no way with the Rascal API to programmatically create queues / exchanges after initialisation. Your only option is to [get a new connection](https://github.com/guidesmiths/rascal#connect) to the broker, create a channel and then assert the queue / exchange, but Rascal won't know anything about it.

**Comment by Ibrahimtrrc** [comment]
hi @cressie176,
thank you for your quick response and sorry for my late one.

is it something you plan to implement ? the problem is that rascal is like the only good library to manage rabbit connections in nodeJS :) ( i'm very gratefull for that btw ). And Rabbot is unmaintained :'(

**Comment by cressie176** [comment]
Hi @Ibrahimtrrc. Sorry it's not something I'm planning to implement at least in the short term. Sure you've already check it out but you can also use https://www.npmjs.com/package/amqp-connection-manager to manage connections with amqplib.

**Comment by Ibrahimtrrc** [comment]
Thanks for that,
rascal was a way easier and more documented. Nice job

**Comment by Ibrahimtrrc** [comment]
I'll close this as it's not an Issue but a missing Feature.

Thank you very much for your fast answers and your advices :)

**Comment by CodeWithOz** [comment]
> Hi @Ibrahimtrrc,
> 
> There's no way with the Rascal API to programmatically create queues / exchanges after initialisation. Your only option is to [get a new connection](https://github.com/guidesmiths/rascal#connect) to the broker, create a channel and then assert the queue / exchange, but Rascal won't know anything about it.

@cressie176 are there any concerns/pitfalls with your suggestion that we should be aware of? I need the same dynamic creation so I want to do what you suggested. But I'd like to be aware of any potential problems. Thanks!

**Comment by cressie176** [comment]
Hi @CodeWithOz 

Rascal isn't really the right tool for this. Since its broker won't know about the exchanges or queues you wont be able to use it to publish or subscribe.
