### ISSUE TITLE
amqplib dependency

### ISSUE THREAD

**Issue by Betisman** [guidesmiths/rascal#66]
I see that this task https://github.com/guidesmiths/rascal/blob/master/lib/amqp/tasks/createConnection.js#L3 requires `amqplib` but this lib is a dev dependency according to the `package.json` https://github.com/guidesmiths/rascal/blob/master/package.json#L21

Doesn't it need to be changed? I've had an issue because of this in a fresh project, I had to `npm install` via our package.json but our project is not using amqplib, but rascal.

**Comment by cressie176** [comment]
Hi @Betisman.

This is by design https://github.com/guidesmiths/rascal/blob/master/CHANGELOG.md#updated-6
