### ISSUE TITLE
Add dynamic subscriptions/publications

### ISSUE THREAD

**Issue by kirly-af** [guidesmiths/rascal#67]
Is there any way to add more publications (ie. queues) to the Broker after it has been created?
It seems that the configuration is static but in my use case I need a way to dynamically create queues.

Example:
* I have 3 categories that I map to 3 publications
* I create the broker
* 5 minutes later, a new category is added, I should create a new publication for it
=> Any way I can do this without re-creating the whole broker instance ?

**Comment by cressie176** [comment]
Hi @kirly-af,
No - rascal is config driven only. This feature has been requested a couple of times, but I don't think it's viable - if the application restarted Rascal would have no way to know what the dynamic configuration should have been.

**Comment by kirly-af** [comment]
Hi @cressie176,

Thank you for your reply. What would be your recommendation for my use case then?
I can give you a more realistic example (though not accurately matching the actual details of my use case):

1. I have 3 users
2. I want to have a consumer dedicated to each user
3. A user is removed from my DB, I want to cancel and/or remove its consumer
4. A user is added to my DB, I want to add a dedicated consumer for it

What would be the design for this, provided I don't want to restart the service to reload the configuration?

**Comment by cressie176** [comment]
Hi @kirly-af,
I think your best approach is to use amqplib natively rather than rascal. Rascal is `a config driven wrapper around amqplib` - it's not designed for dynamic configuration. Sorry.
