### ISSUE TITLE
Allow webpacking by explicitly requiring tasks

### ISSUE THREAD

**Issue by rossj** [guidesmiths/rascal#68]
At the moment, webpack does not quite work with Rascal, as it requires the task files dynamically, which webpack does not understand:

 https://github.com/guidesmiths/rascal/blob/6f23d6f43d3bc118d303dc630f0f71dfd330f55a/lib/amqp/tasks/index.js#L4

If this was changed to explicitly require the individual tasks, then I think webpack would work with this module.

To further explain my use case, I have a large project that uses Rascal for various services. The project is structured as a single code base, with multiple entrypoints, and we generate a separate webpack bundle for each service, which then become essentially the deployment artifacts. At this time, we have to specifically skip webpacking rascal, and then separately include an npm-installed webpack in each service's container.

What do you think about explicitly / statically requiring the tasks? I would be happy to work on PR if you think this is a good idea.

**Comment by cressie176** [comment]
Hi @rossj,

I'm fine with your suggestion and would be delighted with a PR. Please keep to ES5 though to be consistent with the rest of the rascal code base.
