### ISSUE TITLE
Messages to publish are lost when RabbitMQ connection fails

### ISSUE THREAD

**Issue by rogatty** [guidesmiths/rascal#72]
I have this simple publication code:

```
const broker = await Rascal.BrokerAsPromised.create(Rascal.withDefaultConfig(config));

broker.on('error', (error) => {
    console.error(`Broker error: ${error.message}`);
});

setInterval(async function() {
      try {
        const publication = await broker.publish('pub', 'hello world');
        publication.on('error', (error) => {
            console.error(`Publication error: ${error.message}`);
        });
      } catch (error) {
        console.error(`Rascal config error: ${error.message}`);
      }
}, 1000);
```

It's running fine until I shutdown the RabbitMQ server. Then I see this error in the logs:
```
Broker error: Connection closed: 320 (CONNECTION-FORCED) with message "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
```

The messages are not published now, obviously. There is no `Publication error` in the logs though, which caused some confusion for me.

When I start the RabbitMQ server, I'd expect the in-meantime messages to be published after Rascal reconnects. This doesn't happen, the messages are lost. If I understand the code correctly they're queued in `poolQueue`: https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L211 but then after reconnection the queue is overridden with an empty one in https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L245

My workaround is to add a local queue and pause/resume it based on the connection status:
```
const broker = await Rascal.BrokerAsPromised.create(Rascal.withDefaultConfig(config));

const messagesToPublishQueue = async.queue((_, next) => {
	next();
}, 1);

messagesToPublishQueue.pause();

broker
    .on('error', (error) => {
        console.error(`Broker error: ${error.message}`);
    })
	.on('connect', () => {
		messagesToPublishQueue.resume();
	})
	.on('disconnect', () => {
		messagesToPublishQueue.pause();
	});

setInterval(async function() {
    messagesToPublishQueue.push(null, async () => {
      try {
        const publication = await broker.publish('pub', 'hello world');
        publication.on('error', (error) => {
            console.error(`Publication error: ${error.message}`);
        });
      } catch (error) {
        console.error(`Rascal config error: ${error.message}`);
      }
    });
}, 1000);
```

**Comment by cressie176** [comment]
Hi @rogatty,

Thanks for posting. I'll have a dig into this later and make sure I understand the issue and what's going on, however I'm not sure the scenario you describe could happen using confirm channels. With a confirm channel (rascal's default). amqplib will wait for broker to acknowledge receipt of the message before yielding. The sequence of actions during [publish](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Publication.js#L80-L98) is...

1. Grabs a channel from either the confirm or regular pools
1. Attach an error listeners to the channel
1. Publish the message (delegates to amqplib)
1. Remove the error listeners from the channel
1. Return the channel (may be deferred if the channel was saturated)
1. Emit any error reported by amqplib
1. Return

I don't see how amqplib would yield (without error) if it had not successfully published the message when using confirm channels.

As can be seen from the above steps, rascal does not internally queue messages pending publication, however it does queue requests to borrow channels from the channel pool. I would be reluctant to internally queue messages and attempting to republish them on disconnection. It could lead to situations where Rascal gave the impression the publish was successful, but in reality had a large stash of messages that would be lost if the application crashed / restarted. Furthermore it would be quite complicated to implement with amqplibs flow control (used to indicate when a channel is saturated, and the user should back off)

**Comment by rogatty** [comment]
@cressie176 when saying
>I'm not sure the scenario you describe could happen using confirm channels

you mean the `Publication error` not being logged? I'm using confirm channels and it happens 🙂 I believe it's because the first action on your list is never finished:
>Grabs a channel from either the confirm or regular pools

It goes like that:

1. [`_publish`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Publication.js#L80-L98) calls `borrowChannelFn` with a callback that would emit the errors reported by amqplib
2. `borrowChannelFn` points to [`borrow`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L205) which pushes the aforementioned callback to [`poolQueue`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L211)
3. If the `poolQueue` isn't paused, the callback is executed and the rest of your list happens

But, when the RabbitMQ connection fails then:

1. `handleConnectionError` calls [`pauseChannelAllocation`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L336)
2. `pauseChannelAllocation` calls [`confirmChannelPool.pause()`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L301)
3. `poolQueue` is paused and our callback waits to be executed


When the RabbitMQ connection is back:
1. `handleConnectionError` calls [`init`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L339)
2. `init` calls [`createChannelPools `](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L60) which calls `createChannelPool`
3. `createChannelPool` [overrides `poolQueue`](https://github.com/guidesmiths/rascal/blob/a68834d46ccc0b476d4530a21368ca2b234348d6/lib/amqp/Vhost.js#L245) which drops our callback queue

>rascal does not internally queue messages pending publication, however it does queue requests to borrow channels from the channel pool

Directly, it queues requests to borrow channels. Indirectly, it also queues messages pending publication, because they're callbacks passed to `borrowChannelFn`.

**Comment by cressie176** [comment]
Thanks for explaining again @rogatty, I understand the issue now. Agree it's a problem that needs fixing.

**Comment by cressie176** [comment]
OK. Think I've fixed it. Basic premise is to never replace the channel pools. If the connection is closed, the channels will automatically be removed from the pool by the channel error/close handler. The pool will either be automatically replenished (depending on configuration) or a new channel will be created when next requested. I tested by tweaking the busy publisher example and manually closing the connection from the management ui. Will push shortly.

**Comment by cressie176** [comment]
Published as rascal@6.0.3

**Comment by rogatty** [comment]
Thank you! The messages previously dropped are now published after reconnection. It works as I'd expect it to, but maybe should be mentioned in the docs so it's clear to everyone.

>I would be reluctant to internally queue messages and attempting to republish them on disconnection. It could lead to situations where Rascal gave the impression the publish was successful, but in reality had a large stash of messages that would be lost if the application crashed / restarted. 

This is exactly what's happening 😉

**Comment by cressie176** [comment]
>> I would be reluctant to internally queue messages and attempting to republish them on disconnection. It could lead to situations where Rascal gave the impression the publish was successful, but in reality had a large stash of messages that would be lost if the application crashed / restarted.

> This is exactly what's happening 😉

Not quite (unless I'm still missing something). Rascal shouldn't have called the callback, so while messages had been queued as a side effect of the event loop, Rascal shouldn't have given the impression that the publish was successful.

**Comment by rogatty** [comment]
Messages are queued and when connection is re-established, they're successfully published. There is no publisher error event emitted.

**Comment by cressie176** [comment]
I was trying to explain that I don't want to give people the impression that just because you call `broker.publish` that the message is guaranteed to be delivered until rascal has executed the callback / resolved the promise. It's still possible for the application to crash or be shutdown before a connection recovers. Under this scenario messages inflight would still be lost.

**Comment by rogatty** [comment]
Understood. It's up to you if and how you want to document the current behaviour 🙂 If someone tries to debug what's happening they'll probably end up here and can learn from the discussion above.

Thanks again for fixing the issue so quickly!
