### ISSUE TITLE
[Question] What would it happen if the acknowledge message from the consumer times out?

### ISSUE THREAD

**Issue by carlosvillademor** [guidesmiths/rascal#74]
Hello @cressie176,

More than an issue, this is a question. 

We have been doing some load test for an application using Rascal. We have seen that sometimes messages hang on RabbitMQ queues as unacknowledged until we restart the consumers. Our theory is the acknowledge message fails due to a ETIMEDOUT or ECONRESET. Is our theory plausible? What are your thoughts? We are thinking to add a timeout, after which, the message would be nacked. Obviously, we would need to be prepared for redeliveries of messages as explained on https://www.rabbitmq.com/confirms.html#automatic-requeueing. The problem would be that the ackOrNack is not a promise we can put into a Promise.all with a timeout, neither does return any value. So I am not sure how we could do this. Do you have any suggestions?

Thanks in advance.

**Comment by carlosvillademor** [comment]
Actually, if there is such a ETIMEDOUT or ECONRESET errors, would ackOrNack call throw an error?

**Comment by cressie176** [comment]
I'm pretty sure if the connection drops (or probably even if the channel dies) RabbitMQ will rollback any unacknowledged messages.

**Comment by carlosvillademor** [comment]
Yes, that is correct, according to the RabbitMQ documentation. And that's what happens when we restart the consumers. The problem is that we think the connection does not drop, neither the channel dies, but we still get a timeout from the load balancer in our infrastructure.

**Comment by cressie176** [comment]
ETIMEDOUT or ECONRESET would be emitted as an error event from the connection, causing amqplib to bork the channel and connection, so I don't think it's that. Furthermore providing you have heartbeats enabled both server and the client to detect situations where the other is not responding and close the connection.

If you're doing load testing, are you sure you're not saturating the event loop, causing the application to be unresponsive? 

The latest version of rascal exposes amqplib's native [flow control](https://github.com/guidesmiths/rascal#flow-control) so this might be of some use in checking when your application is getting saturated. You may also need to configure the channel pool options.

**Comment by carlosvillademor** [comment]
Thanks for the feedback @cressie176. We will keep investigating. We'll check the different options/suggestions you are providing.

**Comment by cressie176** [comment]
FYI There's an example for using flow control with Rascal [here](https://github.com/guidesmiths/rascal/tree/master/examples/busy-publisher)

**Comment by cressie176** [comment]
> The problem would be that the ackOrNack is not a promise we can put into a Promise.all with a timeout, neither does return any value. So I am not sure how we could do this. Do you have any suggestions?

Somehow overlooked this before. Sorry.

I have seen something similar to this in our environment, but only when we were posting data to a SOAP based webservice using a 3rd party library. We were never able to track down the cause, but my assumption was that the library had a bug that meant it never returned, so our application code never invoked ackOrNack. We use Rascal in 100+ microservices and this is the only one that's demonstrated the problem so I'm optimistic that it's a problem with the third party rather than our environment,  Rascal or amqplib.

The solution we chose is very similar to what you were suggesting. Something like...

```js
const once = require('lodash.once');

const subscription = await broker.subscribe('sub-1');

subscription.onMessage(async (message, content, ackOrNack) => {
  const ackOrNackOnce = once(ackOrNack);
  try {
    await Promise.race([
      new Promise((resolve, reject) => {
        setTimeout(reject, 60000).unref();
      }),
      handleMessage(message, content, ackOrNackOnce),
    ]);
  } catch (err) {
    ackOrNackOnce(err);
  }
});
