### ISSUE TITLE
How to declare a queue as lazy?

### ISSUE THREAD

**Issue by dmfaux** [guidesmiths/rascal#79]
👋 I have a number of queues that I need to connect to that have been predeclared as lazy. I cannot seem to find the correct settings to add to the Rascal config file.

What I have unsuccessfully tried:

```
// ...
queues: {
  "this.is.a.queue": {
    options: {
      arguments: {
        "x-queue-mode": "lazy"
        // Also tried queueMode: "lazy"
      }
    }
  }
}
// ...
```
```
// ...
queues: {
  "this.is.a.queue": {
    options: {
      "x-queue-mode": "lazy"
      // Also tried queueMode: "lazy"
    }
  }
}
// ...
```

This is the error that is emitted when attempting to connect:
```
{ Error: Operation failed: QueueDeclare; 406 (PRECONDITION-FAILED) with message
"PRECONDITION_FAILED - inequivalent arg 'x-queue-mode' for queue 'this.is.a.queue'
in vhost '/': received the value 'lazy' of type 'longstr' but current is none"
```

I am happy to update the documentation and submit a pull request once I've solved this 👍

**Comment by cressie176** [comment]
Hi @dmfaux ,

I agree it's not easy to work out and that Rascal would be improved if this was documented. Thanks for the offer of a PR.

Here's and example of how you can define a queue with extensions...
```
"queues": {
  "test_q": {
    "options": {
      "arguments": {
        "x-message-ttl": 65000,
        "x-max-length": 1
      }
    }
  }
}
`````

**Comment by dmfaux** [comment]
Arrrgh! Sorry @cressie176 I see my first example is the correct way to go and would have worked but it seems I have didn't pick up that the error message had changed and no longer was complaining the the queue is declared as lazy but rather the it is NOT declared as lazy but I am trying to connect to it with the argument that is was.... 🤦‍♂ 

Thanks for the prompt reply and the excellent wrapper 🤜 🤛 
I will send through a PR with a doc update as promised
