### ISSUE TITLE
Connected event listener

### ISSUE THREAD

**Issue by duccio** [guidesmiths/rascal#85]
Hello, really great work on Rascal, thanks!

Just a question. I can "create" a broker and add a listener for an error event:

```javascript
const broker = await rascal.BrokerAsPromised.create(rascal.withDefaultConfig(rascalConfigServer))
broker.on("error", onRascalBrokerError)
```

How can I add a listener for "connected" event instead?

Thanks again.

**Comment by cressie176** [comment]
In Rascal, the broker is a wrapper for one or more vhosts, and each vhost manages its own connection. The vhosts emit [connect](https://github.com/guidesmiths/rascal/blob/d8f03a5190d704bd5f41b7a61eb0699e3e331524/lib/amqp/Vhost.js#L47) events, which are [forwarded](https://github.com/guidesmiths/rascal/blob/d8f03a5190d704bd5f41b7a61eb0699e3e331524/lib/amqp/tasks/initVhosts.js#L12) to the broker, however this might not be useful for two reasons...

1. `BrokerAsPromised.create` won't yield until all the connections have been established, so you won't have the opportunity to registered handlers until after the events have been emitted (but you could listen for connect events following a disconnection)
1. There's nothing to tell the broker which vhost the events are from.

What did you want to use the connect event for?

**Comment by duccio** [comment]
Thanks for the reply. I'm interested on "connect event" for logging purpose. Can I assume so that after a try...catch block like this:

```javascript
try {
  const broker = await rascal.BrokerAsPromised.create(rascal.withDefaultConfig(rascalConfigServer))
  broker.on("error", onRascalBrokerError)
} catch (error) {
  onRascalBrokerError(error)
}
```
Rascal is connected to all the virtual hosts? So:

```javascript
try {
  const broker = await rascal.BrokerAsPromised.create(rascal.withDefaultConfig(rascalConfigServer))
  broker.on("error", onRascalBrokerError)
} catch (error) {
  onRascalBrokerError(error)
}

console.log("Rascal connected successful to all the vhosts!")```

**Comment by cressie176** [comment]
Maybe...
```js
try {
  const broker = await rascal.BrokerAsPromised.create(rascal.withDefaultConfig(rascalConfigServer))
  console.log("Rascal connected successful to all the vhosts!")```
  broker.on("error", onRascalBrokerError)
} catch (error) {
  onRascalBrokerError(error)
}
```

**Comment by duccio** [comment]
Yeah, for sure, my mistake. Thanks for confirm that BrokerAsPromised.create won't yield until all the connections have been established.
