### ISSUE TITLE
Electron : setTimeout(...).unref() is not a function

### ISSUE THREAD

**Issue by scottk** [guidesmiths/rascal#89]
There's an issue with Electron where setTimeout does not return anything since it's techinically a "browser", causing .unref() to crash the program in Vhost.js.

I have a fix (just checking if setTimeout contains unref) but can't create a branch.

**Comment by cressie176** [comment]
Hi @scottk,

Thanks for reporting. I wonder whether there are other differences between node and electron. If this was the only incompatibility I'd be fine with your suggested approach, but I'm skeptical that there aren't others. Any thoughts?

**Comment by scottk** [comment]
Not that I can think of....Supposedly a common issue for a lot of different libraries being used in electron - electron uses a browser implementation of setTimeout causing it to not return anything/have any properties. There is a property for electron windows called "nodeIntegration", which still doesn't fix the problem (but does fix others like it)

**Comment by cressie176** [comment]
https://www.electronjs.org/docs/tutorial/application-architecture#using-nodejs-apis says you're right.

I think your proposed solution is sound. Would you consider submitting a PR?

I'm not sure why you weren't able to make a branch - should be a case of 

1. **fork**ing rascal to GitHub account you own
2. cloning locally
3. making the change
4. pushing and creating a PR

The tests do need RabbitMQ running locally. If you have docker installed the easiest way to do this is by typing ```npm run docker``` after cloning rascal.

**Comment by scottk** [comment]
![image](https://user-images.githubusercontent.com/2460233/78695151-ff175680-78fd-11ea-9c3b-494b74a0892f.png)

I updated all locations with setTimeout if that's ok - only the one in Vhost was failing, and only when a connection was broken, but I figured we should cover all of them. Will make the PR now

**Comment by cressie176** [comment]
Published as rascal@9.1.2
