### ISSUE TITLE
connection name

### ISSUE THREAD

**Issue by xpicio** [guidesmiths/rascal#97]
Hello is there any way to setup the `connection_name` property from rascal ?

With amqplib is possibile do it like that:
`amqp.connect('amqp://localhost', {clientProperties: {connection_name: "myFriendlyName"}});`

In this way in rabbitMQ server i can understand who is the owner of the connection:
```
Client properties
connection_name	myFriendlyName
information http://squaremo.github.io/amqp.node
platform Node.JS v12.16.1
product amqplib
version 0.5.5
```

**Comment by cressie176** [comment]
Hi @xpicio,

I'm sure I had this working at one stage, although the code I'm looking at does the following which doesn't seem right...

```
socketOptions: {
  clientProperties: {
    service_name: pkg.name,
    service_description: pkg.description,
    rascal_version: pkg.dependencies.rascal,
  }
}
```

I'll take a proper look later.

**Comment by xpicio** [comment]
yes it's work, thank you 👍
