### ISSUE TITLE
Max Listeners exceeded in Vhost

### ISSUE THREAD

**Issue by aycdinc** [guidesmiths/rascal#99]
I think when an internal reconnect happens, the Vhost object is re-created but the old event listeners are not cleaned up, causing an eventual "memory leak".

`(node:1212) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 paused listeners added to [Vhost]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)`

If the previous Vhost is destroyed or on re-create, Vhost could save the listeners as variables and we could unsubscribe to the events when a reconnect happens. 

I'm not entirely sure the reconnect is where/why this is happening, it just feels likely

**Comment by cressie176** [comment]
Hi @aycdinc,

Thanks for reporting. The only place I can find that Rascal registers an event listener on the vhost, is just before obtaining a channel before publishing a message. After it has obtained the channel, then the listener is removed. I added this recently to forward "paused" events from the vhost to the publication. I think it's possible that if you are publishing messages quite rapidly, the vhost may have more than 11 `paused` event listeners, however this is not actually a problem. I will see if I can reproduce and if so set the max listeners to zero to disable the warning.

**Comment by cressie176** [comment]
That was it. I've disabled the warning and published as Rascal@10.0.1

**Comment by aycdinc** [comment]
Awesome! Thanks, will update. Yeah it wasn't causing problems, just wanted to make sure
